src/main/java/appland/actions/OpenRecentAppMapAction.java, src/main/java/appland/editor/AppMapFileEditor.java, src/main/resources/META-INF/plugin.xml, src/main/resources/messages/appland.properties, src/test/java/appland/actions/OpenRecentAppMapActionTest.java
Closes https://github.com/applandinc/appmap-intellij-plugin/issues/4
The most recently modified file is opened. The modification timestamp of IntelliJ's VirtualFileSystem layer is used. The action is only available when indexes are ready.
=> Action to open the most recently modified AppMap file of a project

CHANGELOG.md, README.md, build.gradle.kts, gradle.properties, plugin-description.md, src/main/resources/META-INF/plugin.xml
To be merged after #16 
- description.md is the source for the plugin's description
- CHANGELOG.md is the source for the change notes
=> Render plugin description and change notes from Markdown files

src/main/java/appland/AppMapPlugin.java, src/main/java/appland/Messages.java, src/main/java/appland/actions/ThrowTestException.java, src/main/java/applang/GitHubErrorHandler.java, src/main/resources/META-INF/plugin.xml, src/main/resources/messages/appland.properties
Closes #12 
The newly created issues automatically have label "user report" attached.
=> Add error report for GitHub URLs

CHANGELOG.md, gradle.properties
- bumping version to 0.3.1
- updating changelog
=> Update for release 0.3.1

src/main/resources/META-INF/plugin.xml
=> Allow dynamic load and unload

CHANGELOG.md, description.md, gradle.properties
=> Release 0.4.1

CHANGELOG.md, src/main/java/appland/editor/AppMapNotificationProvider.java, src/main/resources/META-INF/plugin.xml, src/main/resources/messages/appland.properties
=> Show editor notification when JCEF is unavailable

src/main/java/appland/toolwindow/AppMapTreeModel.java, src/main/java/appland/toolwindow/AppMapWindowPanel.java
Tree is refreshed 500ms after typing in the search text input stopped
Closes  https://github.com/applandinc/appmap-intellij-plugin/issues/45
=> #45: auto-refresh tool window when filter text changes

CHANGELOG.md, gradle.properties, src/main/java/appland/toolwindow/AppMapWindowPanel.java
=> Compatibility with 2021.3

CHANGELOG.md, appland-user-milestones/package-lock.json, appland-user-milestones/package.json, appland/package-lock.json, appland/package.json, gradle.properties
Links to instructions for JavaScript AppMap recording.
=> Chore: updating appmap-js components

.travis.yml, build.gradle.kts
Adds a `.travis.yml` file to enable CI using the default Gradle integration.
It fixes a few things in the Gradle build setup to build successfully on Travis.
=> CI with Travis

src/main/java/appland/AppLandLifecycleService.java, src/main/java/appland/AppMapBundle.java, src/main/java/appland/AppMapPlugin.java, src/main/java/appland/files/AppMapFiles.java, src/main/java/appland/files/AppMapVfsUtils.java, src/main/java/appland/files/FileLocation.java, src/main/java/appland/files/FileLookup.java, src/main/java/appland/toolwindow/AppMapToolWindowFactory.java, src/main/resources/META-INF/plugin.xml
This are a few small commits to make a few minor changes, which are needed later for the install guide PR.
=> Cleanup and minor changes to prepare for the install guide

src/main/java/appland/cli/AppLandCommandLineListener.java, src/main/java/appland/cli/AppLandCommandLineService.java, src/main/java/appland/cli/AppLandDownloadListener.java, src/main/java/appland/cli/AppLandDownloadService.java, src/main/java/appland/cli/AppLandProjectManagerListener.java, src/main/java/appland/cli/AppmapYamlAsyncFileListener.java, src/main/java/appland/cli/CliTool.java, src/main/java/appland/cli/DefaultAppLandDownloadService.java, src/main/java/appland/cli/DefaultCommandLineService.java, src/main/java/appland/cli/DownloadToolsStartupActivity.java, src/main/java/appland/cli/RegisterContentRootsActivity.java, src/main/java/appland/cli/StartServicesAfterDownloadListener.java, src/main/java/appland/config/AppMapConfigFile.java, src/main/java/appland/index/AppMapFolderIndexedRootProvider.java, src/main/java/appland/settings/AppMapApplicationSettings.java, src/main/java/appland/settings/AppMapProjectConfigurable.java, src/main/java/appland/settings/AppMapProjectSettingsForm.form, src/main/java/appland/settings/AppMapProjectSettingsForm.java, src/main/resources/META-INF/plugin.xml, src/main/resources/messages/appland.properties, src/test/data/appmap-config/appmap-no-dir.yml, src/test/data/appmap-config/appmap.yml, src/test/java/appland/cli/CliToolTest.java, src/test/java/appland/cli/DefaultAppLandDownloadServiceTest.java, src/test/java/appland/cli/DefaultCommandLineServiceTest.java, src/test/java/appland/cli/ProjectRefreshUtil.java, src/test/java/appland/cli/TestAppLandDownloadService.java, src/test/java/appland/config/AppMapConfigFileTest.java
(Commits should be merged with "rebase and merge")
Another set of changes for the install guide implementation. Helps to reduce the amount of changes in https://github.com/applandinc/appmap-intellij-plugin/pull/81
=> feat: preparations for the install guide

src/main/java/appland/problemsView/AppMapFindingsAnnotator.java, src/main/java/appland/problemsView/FindingsManager.java, src/main/java/appland/problemsView/FindingsPanelProvider.java, src/main/java/appland/problemsView/FindingsRootNode.java, src/main/java/appland/problemsView/FindingsViewTab.java, src/main/java/appland/problemsView/ScannerProblem.java, src/main/java/appland/problemsView/UnknownFileGroupNode.java, src/main/java/appland/problemsView/UnknownFileNode.java, src/main/java/appland/problemsView/UnknownFileProblemListener.java, src/main/java/appland/problemsView/listener/ScannerFilesAsyncListener.java, src/main/java/appland/problemsView/listener/ScannerFindingsListener.java, src/main/java/appland/problemsView/model/FindingsDomainCount.java, src/main/java/appland/problemsView/model/FindingsFileData.java, src/main/java/appland/problemsView/model/ImpactDomain.java, src/main/java/appland/problemsView/model/ScannerFinding.java, src/main/resources/META-INF/plugin.xml, src/main/resources/messages/appland.properties, src/test/data/findings/appmap-findings.json, src/test/java/appland/problemsView/FindingsManagerTest.java, src/test/java/appland/problemsView/TestFindingsManager.java
(Should be merge with "rebase and merge)
Adds the problems view tab and needed services.
There are a few issues with refresh after changes, which will be fixed in new PRs.
=> feat: AppMap tab in problems view

src/main/java/appland/installGuide/analyzer/languages/PythonLanguageAnalyzer.java, src/test/data/installGuide/sample-projects/python-unittest-multiple-files/pyproject.toml, src/test/data/installGuide/sample-projects/python-unittest-multiple-files/requirements.txt, src/test/data/installGuide/sample-projects/python-unittest-multiple-files/z.py, src/test/java/appland/installGuide/analyzer/PythonLanguageAnalyzerTest.java
=> fix: unittest framework wasn't properly detected

src/main/java/appland/cli/AppLandDownloadService.java, src/main/java/appland/cli/CliTool.java, src/main/java/appland/cli/DefaultCommandLineService.java, src/main/java/appland/files/FileLocation.java, src/main/java/appland/index/ClassMapItemType.java, src/main/java/appland/index/IndexUtil.java, src/main/java/appland/installGuide/analyzer/Features.java, src/test/java/appland/cli/CliToolTest.java, src/test/java/appland/index/StreamingClassMapIteratorTest.java, src/test/java/appland/installGuide/analyzer/LanguageAnalyzerBaseTest.java
A few smaller commits, which are part of the changes for install guide support.
Best reviewed by commit.
(Should be merge with "rebase and merge" to keep the commits)
=> Prepare for install guide support

src/main/java/appland/editor/AppMapFileEditor.java, src/main/java/appland/files/AppMapAsyncFileListener.java, src/main/java/appland/files/AppMapFileChangeListener.java, src/main/java/appland/files/AppMapFileEventType.java, src/main/java/appland/installGuide/InstallGuideEditor.java, src/main/java/appland/notifications/AppMapNotifications.java, src/main/java/appland/settings/AppMapApplicationSettings.java, src/main/java/appland/settings/AppMapProjectSettingsForm.form, src/main/java/appland/settings/AppMapProjectSettingsForm.java, src/main/java/appland/startup/AppLandStartupActivity.java, src/main/java/appland/telemetry/AppInsightsClient.java, src/main/java/appland/telemetry/AppMapRecordListener.java, src/main/java/appland/telemetry/Identity.java, src/main/java/appland/telemetry/Session.java, src/main/java/appland/telemetry/TelemetryService.java, src/main/java/appland/telemetry/data/BaseData.java, src/main/java/appland/telemetry/data/MessageData.java, src/main/java/appland/telemetry/data/Tag.java, src/main/java/appland/telemetry/data/TelemetryEvent.java, src/main/java/appland/toolwindow/AppMapWindowPanel.java, src/main/resources/META-INF/plugin.xml, src/main/resources/messages/appland.properties, src/test/java/appland/files/AppMapAsyncFileListenerTest.java
This change adds some basic telemetry capabilities and includes a few telemetry events
Resolves #86
=> feat: Add telemetry

src/main/java/appland/settings/AppMapApplicationSettings.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/148
=> feat: enable findings by default

gradle.properties
Adds support for the new 2022.3 EAP of the JetBrains IDEs
=> feat: Support 2022.3 EAP

plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java, plugin-core/src/main/java/appland/oauth/AppMapOAuthRequestHandler.java, plugin-core/src/main/java/appland/startup/AppLandStartupActivity.java
Adds sending of telemetry messages for our new oauth handling.
=> Send telemetry messages for oauth authentication

plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/167
=> fix: `ConcurrentModificationException` opening a project

description.md
=> Add terms and conditions to description

plugin-core/src/main/resources/messages/appland.properties
=> Update supported Java versions in error message

plugin-core/src/main/java/appland/toolwindow/installGuide/InstallGuidePanel.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/219
=> fix: update AppMap status labels on EDT after AppMap API key change

plugin-core/src/main/java/appland/files/FileLocation.java, plugin-core/src/test/java/appland/files/FileLocationTest.java
Fixes the error that Code object source files could not be located on Windows.
=> fix: locate source files on Windows

plugin-core/src/main/java/appland/toolwindow/AppMapWindowPanel.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/243
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/238
Provides a data provider for slow (i.e. background) access to the current PsiFile. 2023.1 complains about access to PsiFile in the UI thread (i.e. the EDT).
Using the key for slow data provider is the most compatible way to support both old and new major versions of the IDE.
The exception occurred when navigating or using the context menu of the AppMap tool window.
=> fix: exception "PSI element is provided on EDT" with 2023.1

plugin-core/src/main/java/appland/oauth/AppMapAuthRequest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/250
=> Send user id when signing in to AppMap server

plugin-core/src/main/java/appland/telemetry/AppInsightsClient.java, plugin-core/src/main/java/appland/telemetry/Identity.java, plugin-core/src/test/java/appland/telemetry/IdentityTest.java
Related to https://github.com/getappmap/appmap-intellij-plugin/issues/250, made while investigating the issue.
This is a minor code cleanup to extract a method for common code and to decrease memory usage of GSON, which may be expensive to create.
=> Cleanup identity implementation

gradle.properties
Adds support for the new 2023.2 EAP.
=> Support 2023.2 eap

plugin-core/src/main/java/appland/utils/RunConfigurationUtil.java, plugin-java/src/main/java/appland/execution/AbstractAppMapJavaProgramPatcher.java, plugin-java/src/main/java/appland/execution/AppMapJavaProgramPatcher.java
Minor code cleanup and extract a method to help with the upcoming PR for https://github.com/getappmap/appmap-intellij-plugin/issues/298
=> Minor code cleanup and refactoring

plugin-core/src/main/java/appland/toolwindow/AppMapWindowPanel.java, plugin-core/src/main/resources/messages/appland.properties
=> Improve empty message in the AppMap tool window

plugin-java/src/main/java/appland/execution/AppMapJavaPackageConfig.java
This restricts the search for top-level Java packages to sources of the projects. Previously, the search scope allowed to access packages of libraries.
It also speeds up the search, because now only source roots are searched instead of iterating subdirectories of the content roots. Source roots only contain sources, but content roots may contain much more data.
=> Restrict the search for top-level Java packages

description.md
Also added a link to our security / data handling policy
=> Making JS mentions Node-specific

plugin-core/src/main/java/appland/cli/CliTool.java, plugin-core/src/main/java/appland/index/ClassMapItemType.java, plugin-core/src/main/java/appland/installGuide/InstallGuideViewPage.java, plugin-core/src/main/java/appland/installGuide/analyzer/Score.java, plugin-core/src/main/java/appland/settings/AppMapApplicationSettings.java, plugin-core/src/main/java/appland/telemetry/data/Tag.java, plugin-core/src/main/java/appland/toolwindow/codeObjects/HttpRouteNode.java
This is a minor source code cleanup to move `@Getter` annotations to class-level where applicable.
=> Cleanup: @Getter on enum class

plugin-core/src/main/java/appland/toolwindow/AppMapWindowPanel.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/344
Moves the search input bar and the button to record AppMaps into the AppMaps subpanel. Leaving the action button in the main toolbar of the tool window didn't look good to me.
=> Move text input to filter AppMaps into the AppMaps subpanel

plugin-core/src/main/resources/META-INF/appmap-core.xml
The xml attribute makes the extension point ready for dynamic load/unload.
=> Make our custom extension points dynamic to support dynamic load/unload

plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java, plugin-core/src/main/java/appland/installGuide/InstallGuideViewPage.java, plugin-core/src/test/java/appland/installGuide/InstallGuideViewPageTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/404
With this PR, the green checkmark is added even when the user navigates to "Runtime Analysis" using the webview.
The UI interaction needs a manual test.
=> Update the "Install Guide" panel of the AppMap tool window when the user navigates in the webview

plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/433
This needs manual testing.
=> Show overview of AppMaps findings when "Open the problems tab" is clicked

description.md
=> Updating marketplace listing README

plugin-core/src/main/resources/messages/appland.properties
Changing the action button on the notification to read "View your AppMaps"
=> Update first new map notification message

plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/main/resources/META-INF/appmap-core.xml, plugin-core/src/test/java/appland/AppMapBaseTest.java, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java, plugin-core/src/test/java/appland/cli/TestCommandLineService.java, src/test/data/projects/without_existing_index/appmap.yml, src/test/data/projects/without_existing_index/tmp/appmap/with_modification_date.appmap.json
Closes #436 
Refreshing the parent directory triggers earlier (re)indexing of the AppMap metadata directories.
This results in a quicker UI update of available AppMaps, because the list of AppMaps relies on the metadata indexes.
=> Refresh parent directory of new AppMaps for better user experience

plugin-core/src/main/java/appland/actions/GenerateOpenApiAction.java, plugin-core/src/main/java/appland/execution/AppMapJvmExecutor.java, plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java, plugin-core/src/main/java/appland/startup/AppLandStartupActivity.java, plugin-core/src/main/java/appland/startup/FirstAppMapLaunchStartupActivity.java, plugin-core/src/main/java/appland/telemetry/AppMapRecordListener.java, plugin-core/src/main/java/appland/toolwindow/installGuide/UrlLabel.java, plugin-core/src/main/java/appland/toolwindow/signInView/SignInViewPanel.java, plugin-core/src/main/java/appland/webviews/appMap/AppMapFileEditor.java, plugin-core/src/main/java/appland/webviews/findingDetails/FindingDetailsEditorProvider.java, plugin-core/src/main/java/appland/webviews/findings/FindingsOverviewEditor.java, plugin-gradle/src/main/java/appland/execution/AppMapGradleAgentRunner.java, plugin-java/src/main/java/appland/execution/AbstractAppMapJavaAgentRunner.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/424
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/398
This PR removes most of the telemetry message. Please refer to [this comment](https://github.com/getappmap/appmap-intellij-plugin/issues/398#issuecomment-1721241742) for a list of the removed messages.
=> Remove telemetry except of messages, which may indicate a bug in our code

README.md, description.md
This PR corrects the minimum required version and a few minor things.
=> Update Readme and Marketplace description

plugin-core/src/main/java/appland/AppMapPlugin.java, plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/main/java/appland/cli/LoggingProcessAdapter.java, plugin-core/src/main/java/appland/index/AppMapIndexedRootsSetContributor.java, plugin-core/src/main/java/appland/notifications/AppMapNotifications.java, plugin-core/src/main/java/appland/oauth/AppMapKeyRemoteValidator.java, plugin-core/src/main/java/appland/oauth/AppMapLocalKeyValidator.java, plugin-core/src/main/java/appland/oauth/AppMapLoginByKeyAction.java, plugin-core/src/main/resources/META-INF/appmap-core.xml, plugin-core/src/main/resources/messages/appland.properties, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java, plugin-core/src/test/java/appland/oauth/AppMapKeyRemoteValidatorTest.java, plugin-core/src/test/java/appland/oauth/AppMapLocalKeyValidatorTest.java
Brian has tested the release candidate, so we're ready to merge `develop` into `main` to release a new JetBrains plugin.
=> New JetBrains Plugin release (12/11/2023)

plugin-core/src/main/java/appland/upload/AppMapUploader.java
2023.3 is handling the resolving of sub paths more strictly which caused our uploader test to fail.
This PR is updating the resolving of sub paths to work with all SDKs we're supporting.
=> Fix AppMapUploaderTest for 2023.3

plugin-core/src/main/java/appland/execution/AppMapJvmExecutor.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/555
Updates compatibility to Java 21.
=> Support Java 21 in the plugin

plugin-java/src/main/java/appland/execution/AbstractAppMapJavaAgentRunner.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/565
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/564
This is a workaround for the exceptions linked above.
As far as I can tell the AppMap plugin is calling `getJavaParameters()` correctly, because this method is handling its own `ReadAction`. The exceptions indicate that `getJavaParameters()` did not expect that a ReadAction is required and therefore did not use it. The code called in the stacktraces still expect a `ReadAction` and we're now falling back to use it if the first call of `getJavaParameters()` caused an exception.
I'm unable to reproduce the exception locally, but I'm confident that this is fixing the problem.
=> Workaround for exception "Read access is allowed from inside read action"

gradle.properties, plugin-core/src/main/java/appland/files/AppMapFiles.java, plugin-core/src/main/java/appland/index/AppMapFindingsUtil.java, plugin-core/src/main/java/appland/installGuide/analyzer/LanguageResolver.java
2024.1 eap5 changed some API of the SDK. This pull requests adapts to the modifications while retaining compatibility with the older versions.
=> Fix compatibility with 2024.1 eap5

gradle.properties
With this PR, CI is verifying against the latest 2024.1 eap.
=> Verify against latest 2024.1 eap

.travis.yml
This reverts commit 22ad620acd8bce9c34471596d1f039a287d38afe.
=> Bring back Travis for semantic release

plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/597
#597 contains a stacktrace of a deadlock. `stopAll` was called on the EDT and waiting on the service lock and another thread, which locked the service, was waiting on the EDT.
Uninstalling and unlading a plugin for an update is also disposing the services of the JetBrains plugin, i.e. `dispose()` modified by this PR is called.
(Testing this fix for the deadlock is not implemented, because it's difficult and would require mocking a few services.)
=> Don't terminate AppMap processes on the EDT

plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java
The restart did not work properly. 
It was always using the same delay (5000ms) and did not stop after the 3rd restart attempt. The bug was, that the next restart delay was stored with the already terminated process.
This PR makes the code more clear and stores the restart delay with the new, restarted process.
=> Properly restart crashed AppMap processes with a longer delay

plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java
Tests that the CLI processes are properly started when appmap.yml is created and stopped when it's removed again.
This reactivates and fixes a previously available, but unstable test.
=> Test process handling with appmap.yml

CHANGELOG.md, description.md, gradle.properties, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java, plugin-java/src/main/java/appland/javaAgent/AppMapJavaAgentDownloadService.java, plugin-java/src/main/java/appland/javaAgent/GitHubRelease.java, plugin-java/src/main/java/appland/javaAgent/MavenRelease.java, plugin-java/src/main/java/appland/javaAgent/Release.java, plugin-java/src/test/java/appland/javaAgent/AppMapJavaAgentDownloadServiceProxyTest.java, plugin-java/src/test/java/appland/javaAgent/AppMapJavaAgentDownloadServiceTest.java
=> Download the Java agent from Maven Central

plugin-core/src/main/java/appland/files/AppMapFiles.java
Better logging for https://github.com/getappmap/appmap-intellij-plugin/issues/654
This adds the cause to the logged error, which should help to find out what's wrong here
=> Log cause when AppMap failed to load

gradle.properties, plugin-core/src/main/java/appland/actions/AppMapDocumentationAction.java, plugin-core/src/main/java/appland/files/AppMapFiles.java, plugin-core/src/main/java/appland/files/FileLookup.java, plugin-core/src/main/java/appland/problemsView/FindingsManager.java, plugin-core/src/main/java/appland/settings/AppMapProjectSettingsService.java, plugin-core/src/main/java/appland/toolwindow/runtimeAnalysis/RuntimeAnalysisModel.java, plugin-core/src/main/java/appland/webviews/WebviewEditorIconProvider.java, plugin-core/src/main/java/appland/webviews/navie/NavieCodeSelection.java, plugin-core/src/main/java/appland/webviews/navie/NavieEditorProvider.java, plugin-core/src/main/resources/META-INF/appmap-core.xml, plugin-core/src/test/java/appland/index/ClassMapTypeIndexTest.java, plugin-java/src/main/java/appland/execution/AbstractAppMapJavaProgramPatcher.java, plugin-java/src/main/java/appland/execution/AppMapJavaPackageConfig.java, plugin-java/src/main/java/appland/javaAgent/AppMapJavaAgentDownloadService.java, plugin-java/src/main/resources/META-INF/appmap-java.xml, plugin-java/src/test/java/appland/javaAgent/AppMapJavaAgentDownloadServiceProxyTest.java
Clean up some of the warnings shown by IntelliJ.
Removes use of deprecated API.
=> Source code cleanup

plugin-core/src/main/resources/META-INF/appmap-core.xml
The class is already annotated with `@Service`
=> Drop incorrect applicationService declaration

.appmapignore, plugin-java/src/main/java/appland/execution/AppMapJavaConfigUtil.java, plugin-java/src/main/java/appland/execution/AppMapJavaPackageConfig.java, plugin-java/src/test/java/appland/execution/AppMapJavaPackageConfigTest.java
When generating the default `appmap.yml`, make sure only source directories are included.
Fixes #690
=> fix: only include source directories in config

plugin-core/src/main/java/appland/files/AppMapFiles.java, plugin-core/src/main/java/appland/webviews/appMap/AppMapFileEditor.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/663
This PR
- always adds the `stats` property to the JSON, which is passed to the AppMap webview. If the CLI failed to return the stats, then an empty array is used for `stats`
- does not pass AppMap property `findings` to the AppMap webview for giant AppMaps, but only for regular and large AppMap files. Previously, findings were always attached
Although the old code already added `stats`, it wasn't always added. 
This PR now follows the VSCode plugin's code more closely.
This is what I'm seeing for large AppMaps (tested locally by changing the threshold, I don't have a giant AppMap file available here):
=> Improve handling of giant AppMaps in AppMaps webview

plugin-core/src/main/java/appland/javaAgent/AppMapJavaAgentDownloadService.java, plugin-core/src/test/java/appland/javaAgent/AppMapJavaAgentDownloadServiceProxyTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/643
This PR adds a fallback to the agent JAR download.
If the download from the remote locations failed, then the bundled agent jar is copied to the agent.jar location in the user's home directory.
Because the bundled jar file name doesn't contain the version, we copy the bundled file to `$HOME/.appmap/lib/java/appmap.jar` and not to something like `$HOME/.appmap/lib/java/appmap-1.2.3.jar`.
The bundled jar is only copied to the local location if it does not yet exist, i.e. a previously downloaded version is not replaced with the bundled jar if downloading the latest jar failed.
=> Copy bundled agent.jar file if download of the latest version failed

appland-install-guide/dist/main.js.LICENSE.txt, appland-install-guide/package.json, appland-install-guide/webpack.config.js, appland-install-guide/webview.js, appland-install-guide/yarn.lock, appland-navie/dist/main.js.LICENSE.txt, appland-navie/index.html, appland-navie/package.json, appland-navie/webpack.config.js, appland-navie/webview.js, appland-navie/yarn.lock, plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java, plugin-core/src/main/java/appland/installGuide/analyzer/languages/JavaScriptLanguageAnalyzer.java, plugin-core/src/main/java/appland/installGuide/analyzer/languages/PythonLanguageAnalyzer.java, plugin-core/src/main/java/appland/installGuide/analyzer/languages/RubyLanguageAnalyzer.java, plugin-core/src/main/java/appland/webviews/navie/NavieEditor.java, plugin-core/src/main/java/appland/webviews/navie/NavieEditorProvider.java, plugin-core/src/main/java/appland/webviews/navie/NaviePromptSuggestion.java, plugin-core/src/test/java/appland/installGuide/analyzer/JavaScriptLanguageAnalyzerTest.java, plugin-core/src/test/java/appland/installGuide/analyzer/PythonLanguageAnalyzerTest.java, plugin-core/src/test/java/appland/installGuide/analyzer/RubyLanguageAnalyzerTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/737
=> Support prompt passed from install instructions to Navie

README.md, description.md
CLOSES: https://github.com/getappmap/applandinc.github.io/issues/1445
This updates the readme and `description.md` file for the jetbrains plugin. Some of this content gets mirrored into the marketplace page.
=> Update description and readme

README.md
This fixes https://github.com/getappmap/appmap-intellij-plugin/issues/763
Ensure https://github.com/getappmap/applandinc.github.io/pull/1506 is merged before releasing this.
=> fix: update readme with png images instead of webp

appland-navie/package.json, appland-navie/webview.js, appland-navie/yarn.lock, plugin-core/src/main/java/appland/webviews/navie/NavieEditor.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/810
Adds handling of the new Navie `click-link` webview message.
The link received from the webview is first stripped of a `file://` prefix and then looked up as a relative path in the project. This lookup is using the same method as the handler of `open-location`.
I've tested this with the `@search` command.
=> Update Navie webview and support `click-link`

description.md
Adds references to the new image assets for pinning context.
=> add references to new files for pinning context

appland-navie/index.html, appland-navie/package.json, appland-navie/yarn.lock
This feature flags the subscription status messages (default off)
=> fix: Update @appland/components to v4.43.2

plugin-copilot/src/main/java/appland/copilotChat/NavieCopilotChatRequestHandler.java, plugin-copilot/src/main/java/appland/copilotChat/copilot/CopilotChatSession.java, plugin-copilot/src/main/java/appland/copilotChat/copilot/CopilotModelDefinition.java, plugin-copilot/src/test/java/appland/copilotChat/copilot/CopilotModelDefinitionTest.java, src/test/data/copilot/model_2025-01-21.json
The structure of the remote JSON of the `/models` endpoint changed. This prevented parsing of the models and that broke the Copilot integration.
This PR makes the parsing of model JSON less strict and adds a test case with the current remote data.
=> In the integration with Copilot, loading the models failed

plugin-core/src/main/java/appland/webviews/navie/NavieEditor.java
Related to https://github.com/getappmap/appmap-intellij-plugin/issues/848
Previously, the Navie UI was only shown when the IDE finished indexing.
Especially at startup or when libraries are indexed, this can cause a large delay between opening Navie and the time the Navie UI is displayed.
This PR fixes this problem by detecting dumb mode. Properties are refreshed after the IDE turned into smart mode.
=> Don't delay Navie UI until IDE finished indexing

plugin-core/src/main/java/appland/rpcService/DefaultAppLandJsonRpcService.java
This pull request introduces logging functionality to the `DefaultAppLandJsonRpcService` class in the `plugin-core` module. The changes include the creation of a log file for the JSON-RPC server and methods to handle logging of output and process termination events.
The log file can be found in the IntelliJ log directory:
https://github.com/user-attachments/assets/c1aba567-ed33-4abf-b467-f5577fbb2613
Key changes include:
* Added imports for `File`, `FileNotFoundException`, `FileOutputStream`, and `StandardCharsets` to support file operations and character encoding.
* Introduced a `FileOutputStream` instance `OUTPUT_LOG_STREAM` to manage log file output.
* Implemented `createOutputLogStream` method to create and initialize the log file stream.
* Added `logOutput` method to write log …
=> feat: Add logging for the AppMap RPC server

.github/workflows/build.yml, plugin-core/src/test/java/appland/toolwindow/appmap/AppMapModelTest.java, plugin-core/src/test/java/appland/utils/ModelTestUtil.java
As discussed, `appmap-analysis` is unstable and atm there's no fix expected.
=> Disable appmap-analysis on CI
