description.md
Initial draft of the plugin description is in description.md.
Fixes #15
=> DOCS: adding plugin description content

CHANGELOG.md, description.md, gradle.properties
Updated documentation page now points to https://appland.com/docs/quickstart/ for quickstart.
Bumping version to 0.2.2.
=> Docs description update

build.gradle.kts, gradle.properties
This is maintenance work:
- use JetBrains' latest gradle build plugin
- add compatibility for the newly released 2021.2 EAP
2021.2 seems to improve a few things with JCEF, e.g. the zoom level seems to be correct on my system now.
=> Update build system, add compatibility with 2021.2 EAP

build.gradle.kts, gradle.properties, src/main/java/appland/notifications/AppMapNotifications.java
- Fix compilation with latest rc build. This only affect source-compatibility, but not not binary compatibility. As far as I can tell version 0.4.1 is working fine with 2021.2 rc.
- Update to latest gradle-intellij plugin
=> Fix compilation with 2021.2 rc

src/main/java/appland/index/AppMapMetadataIndex.java
Previously, files larger than IntelliJ's limit for code insight were not indexed and thus unavailable in the list of AppMaps.
=> Index .appmap.json files of all sizes

src/main/java/appland/editor/AppMapFileEditor.java, src/main/resources/messages/appland.properties
Closes #70 
This PR adds the needed changes to display an error message for too large files instead of trying to load the content.
The file size limit is user-configurable as a global, application-wide value within the IDE and defaults to 20 megabytes. Only advanced users of the IDE would customize this.
Although it's technically possible to load the complete content instead of the truncated content, this isn't working well with the current implementation.
Currently, the file content is turned into a JS method call string taking the complete content as argument. For large files this (and the needed JSON escaping of the content) makes things memory hungry and slow.
A method call is needed because the JS application is living in a sandboxed environment, which doesn't have access to …
=> Display an error message to the user if the file is too large to be loaded

CHANGELOG.md, README.md, build.gradle.kts, gradle.properties
Closes https://github.com/applandinc/appmap-intellij-plugin/issues/72
This PR updates the build setup to support 2022.1 and to run the plugin verifier against the current EAP of 2022.1.
=> Support 2022.1 EAP releases

CHANGELOG.md, build.gradle.kts, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/main/java/appland/actions/OpenAppMapsAction.java, src/main/java/appland/actions/OpenQuickstartAction.java, src/main/java/appland/milestones/UserMilestonesEditorProvider.java, src/main/java/appland/toolwindow/milestones/UserMilestonesPanel.java
The next major version of JetBrains IDEs is now in beta (2022.2).
This PR 
- updates the Gradle wrapper
- adds compatibility for 2022.2
- hides the user milestones links and webview if unsupported. This happened in the sandboxed IDE of 2022.2 beta
=> Support 2022.2 EAP

src/main/java/appland/index/AppMapMetadata.java
The AppMaps shown in the install guide web view were not sorted in the same way as the VSCode plugin.
=> Sort selected AppMaps in the same way as the VSCode plugin

gradle.properties, src/main/java/appland/editor/AppMapFileEditor.java
The install guide feature needs a newer SDK, because the problems view tab is not extendable in older versions.
This PR drops support for 2021.1 and 2021.2 and updates init of our web view panel to use the API, which is now available with the updated SDK.
=> Drop support for older versions of IDEs, fix init of JCEF panel

CHANGELOG.md, src/main/java/appland/index/ClassMapItemType.java, src/main/java/appland/index/IndexUtil.java
Without this, AppMaps containing external service calls will fail to be indexed.
=> fix: Add external service objects

.releaserc.yml, .travis.yml, build.gradle.kts
Reverts the commit which removed `verifyPlugin` and fixes the gradle setup to only execute `verifyPlugin` for the main module, which is published.
=> Fix `verifyPlugin`

plugin-core/src/main/java/appland/toolwindow/installGuide/InstallGuidePanel.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/142
=> fix: show success icon for "Runtime Analysis" even if only findings with unknown source files were found

plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java
I'm deactivating the unstable test method because there's no obvious reason why it's failing. This is most likely a timing issue and not straight forward to fix.
https://github.com/getappmap/appmap-intellij-plugin/issues/161 tracks the unstable test to make sure that we properly fix this.
=> Deactivate unstable test `assertActiveRoots`

plugin-core/src/main/java/appland/oauth/AppMapAuthRequest.java
`/authn_provider/localhost` has been deprecated and will be removed in the future.
=> fix: Use `/authn_provider` for authentication

plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java
This uses an empty string as fallback for the language name.
The name is used for telemetry property `appmap.project.language`.
=> fix: NPE when the project language could not be found

gradle.properties, plugin-core/src/main/java/appland/execution/AppMapJvmExecutor.java, plugin-core/src/main/java/appland/oauth/AppMapAuthRequest.java
This change:
- Bumps the bundled AppMap agent version to latest
- Adds a parameter to the authentication request indicating the source of the authentication (`JetBrains`). This is used by the backend to determine the description of a users API key.
=> Pre-release tweaks: upgrade the AppMap agent and specify an authentication source during login

plugin-core/src/main/java/appland/files/AppMapAsyncFileListener.java, plugin-core/src/main/java/appland/telemetry/AppMapRecordListener.java
All the file events were coming through as refresh, so no notifications containing create/modify events would ever fire. `AppMapAsyncFileListener` had appeared to be unused due to this.
=> fix: Emit appmap:create events

build.gradle.kts, plugin-core/src/main/java/appland/actions/GenerateOpenApiAction.java, plugin-core/src/main/java/appland/cli/AppLandCommandLineService.java, plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java, plugin-core/src/main/java/appland/installGuide/InstallGuideViewPage.java, plugin-core/src/main/java/appland/settings/AppMapProjectSettings.java, plugin-core/src/main/java/appland/settings/AppMapProjectSettingsForm.java, plugin-core/src/main/java/appland/settings/AppMapSettingsListener.java, plugin-core/src/main/java/appland/toolwindow/installGuide/InstallGuidePanel.java, plugin-core/src/main/java/appland/upload/AppMapUploader.java, plugin-core/src/main/resources/META-INF/appmap-core.xml, plugin-core/src/main/resources/messages/appland.properties, plugin-core/src/test/java/appland/upload/AppMapUploaderTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/163
Still missing:
=> feat: Implement "Generate OpenAPI"

plugin-core/src/main/java/appland/problemsView/listener/ScannerFilesAsyncListener.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/172
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/171
This exception happens when many changes to AppMap files are processed in a short duration. Multiple open projects make it more likely to happen.
Testing this is quite difficult, it very much depends on timing, performance and load of the current machine, and more.
=> fix: avoid exception "Too many non-blocking read actions"

gradle.properties
Can be tested by launching the IDE with the plugin and running a run configuration with the AppMap executor.
I verified that the bundled jar is the new version.
=> Bundle appmap-java agent v1.15.4

build.gradle.kts, gradle.properties
Updates the build setup to use the latest gradle-intellij plugin (always recommended) and adds more logging to STDOUT on Travis to help debug failing tests.
=> Update build to help with debugging CI errors

plugin-core/src/main/java/appland/webviews/appMap/AppMapFileEditor.java, plugin-core/src/main/resources/messages/appland.properties
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/139
Needs #189 , because that PR refactors the code updated by this PR.
This PR fixes an exception, which occurred when a user clicked "Show source" inside an AppMap editor.
=> Locate source file in background thread inside a ReadAction

plugin-core/src/main/java/appland/actions/StopAppMapRecordingAction.java, plugin-core/src/main/java/appland/files/AppMapFiles.java, plugin-core/src/main/java/appland/remote/DefaultRemoteRecordingService.java, plugin-core/src/main/java/appland/remote/RemoteRecordingService.java, plugin-core/src/main/java/appland/remote/StopRemoteRecordingDialog.java, plugin-core/src/main/java/appland/remote/StopRemoteRecordingForm.java, plugin-core/src/main/resources/messages/appland.properties, plugin-core/src/test/java/appland/actions/StopAppMapRecordingActionTest.java, plugin-core/src/test/java/appland/files/AppMapFilesTest.java, plugin-java/src/main/java/appland/execution/AppMapJavaPackageConfig.java, src/test/data/appmap-config/appmap-empty-dir.yml, src/test/data/projects/empty-appMapDir/appmap.yml
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/146
Best reviewed commit by commit.
You can test this by doing a remote recording, e.g. via `Tools > AppLand > ...`. The stop action should pick up the right location the first time it's invoked in a project.
- Cleanup of the code and fix a few minor issues of "stop remote recording". The code needed some care...
- Refactoring to allow fetching the default storage location in the background
- Don't terminate early in "Stop remote recording" if the update of the AppMap name failed (e.g. due to an unknown or invalid encoding of the retrieved AppMap)
- Update the default location of recorded AppMap
The location is now calculated like this:
1. The last used location of "Stop AppMap recording". I retained the old logic, but this …
=> Improve "Stop remote recording" action

.travis.yml
We referenced JDK 11.0.2 in our Travis setup, but this version is not available anymore and broke CI.
The agent added support for JDK 17, so we don't need this workaround anymore.
=> chore: using JDK 17 is supported now by the agent, no need to setup JDK 11

build.gradle.kts, gradle.properties
fix Gradle warnings about incorrect task dependencies, disable test caching, don't run tests of modules in parallel
=> chore: fix Gradle build for development

plugin-core/src/main/java/appland/webviews/SimpleWebviewMessageHandler.java, plugin-core/src/main/java/appland/webviews/WebviewEditor.java, plugin-core/src/main/java/appland/webviews/appMap/AppMapFileEditor.java, plugin-core/src/main/java/appland/webviews/findingDetails/FindingDetailsEditor.java, plugin-core/src/main/java/appland/webviews/findings/FindingsOverviewEditor.java
Preliminary work for https://github.com/getappmap/appmap-intellij-plugin/issues/246
Fixes the responses to webview messages. Previously, the AppMap webview editor implementation skipped responses,, but we should always send it if the message was handled.
=> Simplify JCEF webview message handling

plugin-core/src/main/java/appland/cli/AppLandCommandLineService.java, plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/main/java/appland/files/AppMapFiles.java, plugin-core/src/main/java/appland/webviews/WebviewEditor.java, plugin-core/src/main/java/appland/webviews/appMap/AppMapFileEditor.java, plugin-core/src/main/resources/messages/appland.properties, plugin-core/src/test/java/appland/files/AppMapFilesTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/244
This is best tested with a project containing large and giant AppMaps.
- Executes the AppMap CLI to purge large AppMaps
- Always adds the "stats" property (loaded via AppMap CLI) to the JSON passed to the AppMap webview
- Adds tests to test the CLI with the prune and stats commands
=> Prune large AppMaps using the CLI

plugin-core/src/main/java/appland/oauth/AppMapAuthRequest.java, plugin-core/src/main/java/appland/telemetry/Identity.java
`main` became broken after the latest PR was merged. Most likely this was caused by not rebasing the PR onto latest main to test compilation again. There was no conflict detected by GitHub.
=> Fix compilation of `main`

plugin-core/src/main/java/appland/cli/AppLandCommandLineService.java, plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/main/java/appland/cli/RegisterContentRootsActivity.java, plugin-core/src/test/java/appland/AppMapBaseTest.java, plugin-core/src/test/java/appland/actions/StopAppMapRecordingActionTest.java, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java, plugin-core/src/test/java/appland/index/StreamingClassMapIteratorTest.java, plugin-java/src/test/java/appland/execution/BaseAppMapJavaTest.java
Fixes non-working handling of large AppMaps on Windows. The "stats" command was printing ANSI escape codes to STDOUT, which were breaking JSON parsing. This only happened on Windows, though. Running CI on Windows would have found this problem.
The other commits fix CI on Windows and should also fix the flaky CI with Travis. Background activity, which is often delayed on slow systems, was breaking the tests.
=> Fix support for large AppMaps on Windows

plugin-core/src/main/java/appland/index/ClassMapItemType.java, plugin-core/src/main/java/appland/index/ClassMapTypeIndex.java, plugin-core/src/main/java/appland/index/IndexUtil.java, plugin-core/src/main/java/appland/index/StreamingClassMapIterator.java, plugin-core/src/test/java/appland/index/ClassMapTypeIndexTest.java, src/test/data/classMaps/unexpectedClassMapType/firstMap/classMap.json
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/271
This adds a test and fix to avoid breaking the IDE's index of AppMap class map items if an yet unsupported class map item type is encountered.
=> Don't break index of AppMap code objects for unknown class map item types

plugin-core/src/main/resources/META-INF/appmap-core.xml
The log of the IDE was complaining about the missing ID, which is apparently only in later versions of the platform.
=> Add missing ID to plugin.xml

plugin-core/src/main/java/appland/files/AppMapFiles.java, plugin-core/src/main/java/appland/webviews/appMap/AppMapFileEditor.java
This is a possible remedy for https://github.com/getappmap/appmap-intellij-plugin/issues/259, where a haning IDE was reported. It won't fix the crashing IDE, though.
Loading an AppMap webview executes the stats command with the AppMap CLI tool. 
The execution was not limited and may prevent the successful loading of an editor webview. 
This PR adds a timeout of 20s to restrict the maximum runtime of the stats command. I expect that the stats command is much faster than 20s, but we should avoid a blocking editor, nevertheless.
=> Restrict runtime of the AppMap stats command with a timeout (20s)

plugin-core/src/main/java/appland/problemsView/FindingsManager.java, plugin-core/src/test/java/appland/problemsView/FindingsManagerTest.java, plugin-core/src/test/java/appland/toolwindow/runtimeAnalysis/RuntimeAnalysisModelTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/270
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/182
The reload of finding files uses a cancellable ReadAction, which means that it could be executed multiple times.
The code, which was executed multiple times, had side effects, which could break the UI.
This PR removes the side effects and consistently applies the results collected by the ReadAction to the UI.
Most likely, this is also a fix for https://github.com/getappmap/appmap-intellij-plugin/issues/270, which may be caused by a disposed project.
=> Properly handle reload of finding files to avoid an empty list of findings in the UI

plugin-core/src/main/java/appland/toolwindow/AppMapToolWindowFactory.java, plugin-core/src/main/java/appland/toolwindow/JcefUnsupportedPanel.java, plugin-core/src/main/resources/messages/appland.properties
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/266
This PR displays a panel with an error message instead of attempting to use a JCEF webview on IDEs, where it's unsupported. For example, Android Studio does not support it by default.
I'd be glad for thoughts on the error message and if we should link to a webpage with further details on this or not.
=> Warn about missing support for JCEF webviews 

plugin-core/src/main/java/appland/index/AppMapSearchScopes.java, plugin-core/src/main/java/appland/index/ClassMapTypeIndex.java, plugin-core/src/main/java/appland/index/EverythingExceptLibrariesScope.java, plugin-core/src/main/java/appland/problemsView/FindingsManager.java, plugin-core/src/main/java/appland/toolwindow/installGuide/InstallGuidePanel.java
This is a (minor) performance improvement to locate AppMap files in a project. 
I noticed this problem while investigating some of the new exceptions.
The fix is to use our own, more limited scope instead of `GlobalSearchScope.everythingScope(project);`, which also includes library files. Libraries may add a lot of files, e.g. external JAR files in Java project.
=> Improve performance to look up AppMap files in the project

plugin-core/src/main/java/appland/actions/OpenRecentAppMapAction.java, plugin-core/src/main/java/appland/actions/StopAppMapRecordingAction.java, plugin-core/src/main/java/appland/files/FileLookup.java, plugin-core/src/main/java/appland/index/AppMapMetadataIndex.java, plugin-java/src/main/java/appland/execution/AppMapJavaPackageConfig.java
#275 added methods to declare AppMap search scopes. `main` was changed in the meantime and this PR updates the recently added scopes to use the new AppMap scopes instead.
=> Use new AppMap scopes where possible

plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java, plugin-core/src/test/java/appland/problemsView/listener/ScannerFilesAsyncListenerTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/288
The install command needs a PTY, e.g. to query for user input on the terminal.
This is a regression of https://github.com/getappmap/appmap-intellij-plugin/pull/248. The prune command did not work with a  PTY. This PR adds a test and fix to ensure that the install command is executed with a PTY terminal.
=> Execute the AppMap install command with a PTY

plugin-core/src/main/java/appland/actions/StopAppMapRecordingAction.java, plugin-core/src/main/java/appland/remote/StopRemoteRecordingDialog.java, plugin-core/src/main/java/appland/remote/StopRemoteRecordingForm.form, plugin-core/src/main/java/appland/remote/StopRemoteRecordingForm.java, plugin-core/src/main/java/appland/settings/AppMapProjectSettings.java, plugin-core/src/test/java/appland/actions/StopAppMapRecordingActionTest.java
closes https://github.com/getappmap/appmap-intellij-plugin/issues/289
- Drop the file path input from the dialog of the "Stop Remote Recording" action
- Default to `target/appmap` instead of `tmp/appmap`
The storage location of "Stop Remote Recording" now looks into appmap.yml and then defaults to  `target/appmap` if no `appmap_dir` setting was found.
=> Use better default of storage location of "Stop AppMap recording"

plugin-core/src/main/java/appland/problemsView/FindingsManager.java, plugin-core/src/main/java/appland/problemsView/listener/ScannerFilesAsyncListener.java, plugin-core/src/test/java/appland/problemsView/FindingsManagerTest.java, plugin-core/src/test/java/appland/problemsView/TestFindingsManager.java, plugin-core/src/test/java/appland/problemsView/listener/ScannerFilesAsyncListenerTest.java, plugin-core/src/test/java/appland/toolwindow/runtimeAnalysis/RuntimeAnalysisModelTest.java
Removing the use of `ReadAction.nonBlocking` in `ScannerFilesAsyncListner`, because a non-blocking action may be executed multiple times and this call has side-effects. We're now using a blocking ReadAction in smart mode instead. Such side-effects could cause too few or too many findings.
https://github.com/getappmap/appmap-intellij-plugin/pull/303/commits/5dbe753a05e7e962e5ef894f025c90fba83702c9 cleans up the non-blocking ReadAction of `FindingsManager.reloadAsync()`. It removes the return value (a `Promise`) in favor of the message bus. The return value was complicating our setup and didn't work well with the cancellation of the non-blocking ReadAction (via `.coalesceBy(getClass(), project)`). This should hopefully make our tests more stable. Tests were sometimes failing on my local …
=> Cleanup handling of non-blocking ReadAction

plugin-core/src/main/java/appland/webviews/appMap/AppMapFileEditor.java
I noticed this problem while working on changes to "Stop AppMap recording".
The stop action updates the metadata, which triggers file change listeners.
The AppMap webview editor is created after making those changes, but the file change listeners were (sometimes?) dispatched after the editor was already opened.
This PR avoids to load the content twice, which would especially reduce memory usage and time top open for large recordings.
=> Don't reload AppMap webview if it's not fully initialized yet

plugin-core/src/main/java/appland/problemsView/FindingsManager.java, plugin-core/src/test/java/appland/AppMapBaseTest.java
The reload of findings was breaking because of a threading issue. 
The non-blocking ReadAction cancels the operation after the results are calculated. We used to call `onSuccess()`, which unfortunately may happen after or during the cancellation is triggered. This could cause an empty or an incomplete list of findings at startup.
This fix is hopefully fixing this for good. Unfortunately, I don't know of a reliable way to test this with a unit test.
=> Don't show an empty list of findings after project is opened

build.gradle.kts, plugin-core/src/main/java/appland/AppMapPlugin.java, plugin-core/src/main/resources/messages/appland.properties, plugin-java/src/main/java/appland/execution/AppMapJvmCommandLinePatcher.java, plugin-java/src/main/java/appland/javaAgent/AppMapJavaAgentDownloadActivity.java, plugin-java/src/main/java/appland/javaAgent/AppMapJavaAgentDownloadService.java, plugin-java/src/main/java/appland/javaAgent/GitHubReleaseAsset.java, plugin-java/src/main/resources/META-INF/appmap-java.xml, plugin-java/src/test/java/appland/execution/AppMapJavaAgentRunnerTest.java, plugin-java/src/test/java/appland/execution/BaseAppMapJavaTest.java, plugin-java/src/test/java/appland/javaAgent/AppMapJavaAgentDownloadServiceTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/287
With this PR, the Java agent JAR file is downloaded at startup.
The download is only made if the current IDE provides Java support (i.e. IntelliJ IDEA Ultimate or Community). The agent file is only needed for Java-based run configurations. Limiting the download to Java projects is unreliable IMHO, because projects can contain mixed of any kind of language and Java support may be added after a project is opened.
This follows the implementation of VSCode, as outlined by @ahtrotta :
> 1. If the latest JAR file version already exists on disk, then do nothing and return.
> 2. Look for a file in the target directory called appmap-X.X.X.jar.downloading. If this file already exists, and it's less than 5 minutes old, return and …
=> Download the latest AppMap Java agent at startup

plugin-core/src/main/java/appland/config/AppMapConfigFile.java, plugin-core/src/main/java/appland/utils/YamlUtils.java, plugin-core/src/main/resources/messages/appland.properties, plugin-core/src/test/java/appland/config/AppMapConfigFileTest.java, plugin-gradle/src/main/java/appland/execution/AppMapExternalSystemExtension.java, plugin-java/src/main/java/appland/execution/AbstractAppMapJavaProgramPatcher.java, plugin-java/src/main/java/appland/execution/AppMapJavaPackageConfig.java, plugin-java/src/main/java/appland/execution/AppMapJavaProgramPatcher.java, plugin-java/src/main/java/appland/execution/AppMapJvmCommandLinePatcher.java, plugin-maven/src/main/java/appland/execution/AppMapMavenProgramPatcher.java, src/test/data/appmap-config/appmap-packages.yml
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/299
With this PR, property `appmap_dir` is added to a `appmap.yml` file before a run configuration is executed with "Execute with AppMap". Existing `appmap.yml` files, which don't have the property set, will be updated before the run configuration is executed.
If no path for the property was found, then it defaults to `tmp/appmap`.
Because the appmap.yml is always updated, the property is not passed to the Java agent.
Because there are now more possible exceptions before a run is executed, we're now displaying a notification instead of logging it as an error. Before, we were silently skipping some of the errors without telling the user about it.
=> Set `appmap_dir` when creating an `appmap.yml` file

plugin-core/src/main/java/appland/utils/SystemProperties.java, plugin-core/src/main/resources/messages/appland.properties, plugin-java/src/main/java/appland/javaAgent/AppMapJavaAgentDownloadService.java, plugin-java/src/test/java/appland/javaAgent/AppMapJavaAgentDownloadServiceTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/316
The user home dir is contained in system property `user.home`, not `user.dir`.
This PR keeps the property name in a single place to prevent incorrect use.
Previously, it only appeared to be working, because the working directory (`user.dir`) was often set to the user home directory.
=> Use correct path for user home directory

plugin-java/src/main/java/appland/execution/AppMapJavaPackageConfig.java, plugin-java/src/test/java/appland/execution/AppMapJavaPackageConfigTest.java
It's now creating `appmap_dir: target/build` and not `appmap_dir: target\build` on Windows.
=> Create appmap_dir of a appmap.yml file as system-independent path

plugin-core/src/main/java/appland/webviews/appMap/AppMapFileEditor.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/319
To support the init properties of the Vuew component, this branch is based on https://github.com/getappmap/appmap-intellij-plugin/pull/313, which must be merged first.
The only change on top of the base branch is https://github.com/getappmap/appmap-intellij-plugin/pull/320/commits/38f7f290e09ca5109f8167a9c313e0f3d8d2c99e
=> Show flame graph in AppMap webview

plugin-core/src/main/resources/messages/appland.properties, plugin-java/src/main/java/appland/execution/AbstractAppMapJavaAgentRunner.java
During development and using `gradle runIde` I noticed frequent exceptions and also dead-locks of the UI when I executed the sprint-petclinic application with our "Execute with AppMap" button.
I don't know of a reliable case, but it happened to me mostly when I clicked on the button right after launching the IDE.
The exception does not contain our `appmap` package in the stacktrace, so user reports of it would have been sent to JetBrains and not AppMap.
=> Don't execute JDK validation on the EDT

plugin-core/src/main/java/appland/installGuide/InstallGuideEditorProvider.java, plugin-core/src/main/java/appland/installGuide/InstallGuideListener.java
Part of the changes for https://github.com/getappmap/appmap-intellij-plugin/issues/298
This adds a listener. We need to decouple the action after Install Guide navigation because the action needs Java support, which is an optional plugin and thus isn't available in the core part, where the install guide is implemented.
=> Introduce listener to notify about Install Guide navigation

plugin-core/src/main/java/appland/actions/StopAppMapRecordingAction.java, plugin-core/src/main/java/appland/files/AppMapFiles.java, plugin-core/src/main/java/appland/index/AppMapNameIndex.java, plugin-core/src/main/java/appland/index/AppMapSearchScopes.java, plugin-core/src/main/java/appland/installGuide/projectData/DefaultProjectDataService.java, plugin-core/src/test/java/appland/index/AppMapSearchScopesTest.java, plugin-java/src/main/java/appland/execution/AppMapJavaPackageConfig.java
Part of the changes for https://github.com/getappmap/appmap-intellij-plugin/issues/298
We'll need to call the creation of appmap.yml from another method. This PR cleans up the scope handling to simplify the upcoming changes.
The scope to locate appmap.yml files is now defined in a single place.
=> Improve lookup of existing appmap.yml files

plugin-core/src/main/java/appland/toolwindow/installGuide/UrlLabel.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/329
Now the slightly less colored icon is shown for install guide links.
=> Always show icons of install guide links in the same color

plugin-core/src/main/java/appland/toolwindow/AppMapWindowPanel.java, plugin-core/src/main/java/appland/toolwindow/CollapsiblePanel.java, plugin-core/src/main/java/appland/toolwindow/CollapsiblePanelTitle.java, plugin-core/src/main/resources/messages/appland.properties
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/326
Reorders the panels inside the AppMap toolwindow:
1. Instructions
2. AppMaps
3. Runtime Analysis
4. Code Objects
5. Documentation links
It also fixes the height of the nested components and the distribution of available space if there are collapsed components.
There's still a 1px splitter to change the height of the AppMap panel.
It also updates the icons for the collapsed/expanded state. Previously, the expanded icon was used for the collapsed state.
Reviewing commit-by-commit should work well.
Initial view:
=> Reorder panels in the AppMap toolwindow

gradle.properties, plugin-core/src/main/java/appland/execution/AppMapExecutionListener.java, plugin-core/src/main/java/appland/index/AppMapIndexableFilesContributor.java, plugin-core/src/main/java/appland/index/AppMapIndexedRootsSetContributor.java, plugin-core/src/main/java/appland/index/AppMapWatchedRootsProvider.java, plugin-core/src/main/java/appland/index/IndexUtil.java, plugin-core/src/main/resources/META-INF/appmap-core.xml
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/345, but this is only a partial fix
This adds AppMap output directories as watched roots and adds an indexable file set contributor, which is now the default extension point in 2023.2 to add (excluded) directories to the indexed locations.
This should fix missing items in the AppMap tool window with 2023.2.
=> Sync and watch AppMap directories with 2023.2

plugin-core/src/main/java/appland/utils/RunConfigurationUtil.java
With 2023.2, a read action is required. Earlier versions (tested with IC-2021.3.3) did not need it.
=> Use read action to fix exception with 2023.2

plugin-java/src/main/java/appland/execution/AppMapPatcherUtil.java
The assert was added with #348 , but is too strict when it's launched on the event dispatch thread.
This happened for Gradle project.
=> Don't check read access on the EDT

plugin-gradle/src/main/java/appland/execution/AppMapExternalSystemExtension.java, plugin-java/src/main/java/appland/execution/AbstractAppMapJavaProgramPatcher.java, plugin-java/src/main/java/appland/execution/AppMapJavaConfigUtil.java, plugin-java/src/main/java/appland/execution/AppMapPatcherUtil.java, plugin-maven/src/main/java/appland/execution/AppMapMavenProgramPatcher.java
Adds better fallback path for projects based on Maven or Gradle.
Especially Gradle projects have a complex structure. The root module does not have an output directory, only modules "main" or "test" have one attached (for spring-petclinic). Because we only receive the root module (without an output path), we were using "tmp/appmap" as fallback, but we need to use "target/appmap" for Gradle.
This adds a similar fallback for Maven based run configurations.
Unfortunately, I'm not aware of a way to run unit tests based on Gradle or Maven run configurations. The SDK's gradle plugin does something similar, but the test suite is not provided with the SDK and replicating it is out of scope (in my opinion).
=> Better fallbacks for AppMap output directory

.travis.yml
Don't execute Travis's default commands `./gradlew assemble` and `./gradlew check`.
This should speed up the Travis jobs.
=> Fix Gradle with Travis

build.gradle.kts
For unknown reasons ` if (!project.gradle.startParameter.isOffline) { ... }` prevented that the AppMap agent was attached on GitHub Actions. We're now always attaching it. When we switch to the official AppMap Gradle plugin, we don't have to care about the offline mode, anyways.
=> Always attach AppMap agent

plugin-core/src/main/java/appland/files/AppMapFiles.java, plugin-core/src/main/java/appland/problemsView/FindingsManager.java, plugin-core/src/main/java/appland/problemsView/FindingsUtil.java, plugin-core/src/main/java/appland/problemsView/ScannerProblem.java, plugin-core/src/main/java/appland/problemsView/model/FindingsMetadata.java, plugin-core/src/main/java/appland/problemsView/model/ScannerFinding.java, plugin-core/src/main/java/appland/problemsView/model/ScannerFindingEvent.java, plugin-core/src/main/java/appland/problemsView/model/ScannerHttpRequestEvent.java, plugin-core/src/main/java/appland/toolwindow/runtimeAnalysis/nodes/AppMapProjectFindingsNode.java, plugin-core/src/main/java/appland/toolwindow/runtimeAnalysis/nodes/DateBucketNode.java, plugin-core/src/main/java/appland/toolwindow/runtimeAnalysis/nodes/FailedAndSuccessfulFindingsNode.java, plugin-core/src/main/java/appland/toolwindow/runtimeAnalysis/nodes/FindingLocationNode.java, plugin-core/src/main/java/appland/toolwindow/runtimeAnalysis/nodes/FindingsGroupNode.java, plugin-core/src/main/java/appland/toolwindow/runtimeAnalysis/nodes/ImpactDomainNode.java, plugin-core/src/main/java/appland/toolwindow/runtimeAnalysis/nodes/RootNode.java, plugin-core/src/main/java/appland/webviews/appMap/AppMapFileEditor.java, plugin-core/src/main/java/appland/webviews/findingDetails/FindingDetailsEditorProvider.java, plugin-core/src/main/java/appland/webviews/findings/FindingsOverviewEditor.java, plugin-core/src/test/java/appland/problemsView/ScannerProblemTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/368
This PR enhances the findings tree of "Runtime Analysis" to also show findings, which don't have a source files. This matches VSCode's implementation.
This also fixes the display label of findings based on HTTP requests, because they were displayed incorrectly when I tested this PR with spring-petclinic. The updated implementation follows [VSCode's code](https://github.com/getappmap/vscode-appland/blob/694feea75f046d3a9b8179727ab249ec2811690a/src/tree/findingsTreeDataProvider.ts#L128).
=> Show findings without source file in Runtime Analysis panel

plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java, plugin-core/src/main/java/appland/installGuide/InstallGuideEditorProvider.java, plugin-core/src/main/java/appland/settings/AppMapProjectSettings.java, plugin-core/src/main/java/appland/settings/AppMapSettingsListener.java, plugin-core/src/main/java/appland/toolwindow/installGuide/InstallGuidePanel.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/339
When the user navigates to the page, it should be shown as completed. This wasn't implemented so far.
This also updates the update logic for the "Runtime Analysis" step displayed in the AppMap tool window. Previously, it was marked as done if there was at least one finding. But this implementation was different to VSCode and also different to the logic used for the status of the webview step (i.e. the other change of this PR).
=> Show "Runtime Analysis" step as completed when the page is opened for the first time

plugin-core/src/main/java/appland/index/AbstractAppMapMetadataFileIndex.java, plugin-core/src/main/java/appland/index/IndexUtil.java
Adds more debug information for AppMap metadata indexes to help with debugging, e.g. when no AppMaps show up in the AppMap toolwindow.
Cleans some of the base class of AppMap metadata indexes to follow the SDK's way of handling the indexer, for example.
=> Debug information for AppMap metadata indexes

build.gradle.kts, plugin-core/src/main/java/appland/index/BasicAppMapMetadataExternalizer.java, plugin-core/src/main/java/appland/index/IndexUtil.java, plugin-core/src/test/java/appland/AppMapBaseTest.java, plugin-core/src/test/java/appland/index/AppMapMetadataIndexTest.java, plugin-core/src/test/java/appland/index/AppMapNameIndexTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/397
This fixes a user-reported exception. I'm not entirely sure how `name` of metadata.json could become empty. This PR supports the `null` value during indexing to now throw an exception.
This PR adds a test and a few necessary modifications to allow creation of AppMap metadata.json with a `null` name property value in our tests.
=> Fix NPE caused by a `null` value for the name property of AppMap metadata.json

plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/main/java/appland/config/AppMapConfigFileListener.java, plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java, plugin-core/src/main/java/appland/oauth/AppMapLoginAction.java, plugin-core/src/main/java/appland/problemsView/FindingsPanelProvider.java, plugin-core/src/main/java/appland/settings/AppMapApplicationSettings.java, plugin-core/src/main/java/appland/settings/AppMapProjectSettingsForm.form, plugin-core/src/main/java/appland/settings/AppMapProjectSettingsForm.java, plugin-core/src/main/java/appland/settings/AppMapSettingsListener.java, plugin-core/src/main/java/appland/startup/AppLandStartupActivity.java, plugin-core/src/main/java/appland/toolwindow/installGuide/InstallGuidePanel.java, plugin-core/src/main/java/appland/toolwindow/runtimeAnalysis/RuntimeAnalysisModel.java, plugin-core/src/main/java/appland/toolwindow/runtimeAnalysis/RuntimeAnalysisPanel.java, plugin-core/src/main/resources/messages/appland.properties, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/388
This PR removes the setting "Enable findings (experimental)" and always enables the support for AppMap findings:
- The AppMap scanner process is always launched, along with the AppMap indexer
- Telemetry messages `analysis:enable` and `analysis:disable` are not sent anymore, because the user can't toggle it anymore
- The Runtime Analysis panel does not display an empty text anymore. The empty text is shown if no node is visible in the tree. This doesn't happen anymore because of the "Findings overview" node. Previously, the node was hidden if the setting was turned off and a text with sign in instructions was shown.
=> Always enable AppMap findings in the AppMap tool window

plugin-core/src/main/java/appland/startup/AppLandStartupActivity.java, plugin-core/src/main/java/appland/startup/DynamicPluginListener.java, plugin-core/src/main/java/appland/startup/ShowAppLandToolWindowStartupActivity.java, plugin-core/src/main/java/appland/toolwindow/AppMapToolWindowFactory.java, plugin-core/src/main/resources/META-INF/appmap-core.xml
Closes https://github.com/getappmap/board/issues/293
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/400
This PR needs manual testing.
I manually tested this myself with PyCharm 2023.2 and IntelliJ Community 2021.2.
Previously, the "Install Guide" webview was opened at first launch. This happened even if the user was not yet signed in.
Now, the AppMap tool window is shown instead at first launch. The tool window displays the "sign in" webview.
Test instructions:
- The AppMap tool window must open when the first project is opened after the AppMap plugin was installed. It must display the "Sign in" page.
- The AppMap tool window must NOT be shown again when another project is opened or the IDE is restarted after the initial launch. You need to hide the AppMap tool window …
=> Open AppMap toolwindow when the plugin is launched for the first time

plugin-core/src/test/java/appland/AppMapBaseTest.java, plugin-core/src/test/java/appland/index/AppMapSearchScopesTest.java, plugin-core/src/test/java/appland/problemsView/listener/ScannerFilesAsyncListenerContentRootTest.java, plugin-java/src/main/java/appland/execution/AppMapJavaPackageConfig.java, plugin-java/src/test/java/appland/execution/AppMapJavaPackageConfigTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/385
`appmap.yml` was overridden with a new configuration because the search scope to locate existing configurations did not contain all content roots of a module. 
This PR fixes the bug and adds test for relative and absolute input paths to define the appmap_dir value. The `appmap_dir` value is always output as a relative path, as before. This PR also corrects an issue with the handling of relative path values, which was discovered by the new tests.
=> Don't override appmap.yml with new values when it's updated

.github/workflows/appmap-analysis.yml, plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/main/java/appland/cli/IndexerEventUtil.java, plugin-core/src/test/java/appland/cli/IndexerEventUtilTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/366
This PR contains tests for the parsing of `Indexed` events.
The plugin now listens to `Indexed ` events emitted by the AppMap indexer tool. 
This is used to detect new or changed AppMap indexes more reliably. The existing implementation to convince the IDE to index AppMap data is left untouched.
The process listener triggers an async refresh of the file cache and data based on it, e.g. of our file-based indexes.
=> Refresh local filesystem after AppMap indexes were create or updated

plugin-core/src/main/java/appland/webviews/WebviewEditor.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/412
The exception popped up while testing on Windows. Most likely, the slowness of the Windows VM made it more likely to occur.
I don't know of a way to test this. It depends on the timing of a background operation, which can't be controlled by our testing code or a tester.
=> Handle disposed webview editor

.gitignore, appmap.yml, build.gradle.kts, plugin-gradle/src/main/java/appland/execution/AppMapExternalSystemExtension.java, plugin-java/src/main/java/appland/execution/AbstractAppMapJavaProgramPatcher.java, plugin-java/src/main/java/appland/execution/AppMapJavaConfigUtil.java, plugin-java/src/main/java/appland/execution/AppMapJvmCommandLinePatcher.java, plugin-java/src/main/java/appland/execution/AppMapPatcherUtil.java, plugin-maven/src/main/java/appland/execution/AppMapMavenProgramPatcher.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/408
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/419
This updates the creation and update of appmap.yml to always set `tmp/appmap` as value of the `appmap_dir` property, regardless of the build system. Manual setup via IntelliJ project and imports or Maven or Gradle project all default to `tmp/appmap`.
It also removes the passing of `appmap.output.directory` to the agent. Only `appmap.yml` contains the output directory now.
This PR does not:
- update .gitignore or similar files
- update the "exclude folder" setting of the IDE for the new `tmp/appmap` folder
**Note**
This may only be merged after https://github.com/getappmap/appmap-java/issues/210 was published in a release of the AppMap Java  agent.
=> Always use tmp/appmap as AppMap output directory

plugin-core/src/main/java/appland/GitHubErrorHandler.java
Fixes a minor issue in the error reporter. It's now sending the last executed action as it should.
=> The last executed action ID wasn't sent with our error reports

.github/workflows/build.yml, plugin-core/src/main/java/appland/problemsView/FindingsManager.java, plugin-core/src/test/java/appland/AppMapBaseTest.java, plugin-core/src/test/java/appland/toolwindow/codeObjects/CodeObjectsModelTest.java, plugin-java/src/main/java/appland/execution/AppMapJavaPackageConfig.java
Closes #261  
This adds CI support for Windows and macOS using GitHub Actions.
- I added a few fixes to our tests to successfully run on Windows. Some test errors only happened, because of (apparently) dramatically slower Windows machines, e.g. background thread activity long after a project was disposed by a test.
- With the default platform version tests on Windows failed. The AppMap CLI processes failed to terminate and continued to run. The running processes locked the `tmp/appmap` dir, which then prevented to successfully terminate and cleanup tests using AppMap data. I wasn't able to reproduce or to find a working fix. Building against a later JetBrains platform version worked, though. My assumption is, that the later SDKs fixed process termination on Windows.
- I manually verified …
=> Execute GitHub Actions on Windows and macOS

plugin-core/src/main/java/appland/files/AppMapFileChangeListener.java, plugin-core/src/main/java/appland/notifications/AppMapNotifications.java, plugin-core/src/main/java/appland/notifications/FirstAppMapListener.java, plugin-core/src/main/java/appland/settings/AppMapApplicationSettings.java, plugin-core/src/main/java/appland/startup/DynamicPluginListener.java, plugin-core/src/main/java/appland/startup/FirstAppMapLaunchStartupActivity.java, plugin-core/src/main/resources/META-INF/appmap-core.xml, plugin-core/src/main/resources/messages/appland.properties
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/432
Displays a notification when the first AppMap was created.
- It does not check if the user is signed in
- The notification is NOT shown for existing users (`isFirstStart == false`) 
- It displays the "Explore AppMaps" page when the user clicks on the link in the notification
- The notification is only displayed when a new AppMap file is created while the matching project is opened with the AppMap plugin. If a project already contains AppMap files at first startup, then no notification is displayed for these AppMaps.
Possible changes:
- We could display a title and AppMap icon for the notification. Currently, only the message content is shown.
=> Notifiy user about first AppMap

plugin-core/src/main/java/appland/GitHubErrorHandler.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/423
This PR enforces a https connection to send error reports to the GitHub issue page. Thanks to @augustd for pointing this out.
I've manually tested this.
It would be possible to write a test with a local mock server, but that would take some time, esp. with the enforced https connection.
It's not possible to let external testers test it because they would have to trigger an exception in the plugin's code.
=> Enforce https URL for error reports sent as GitHub issues

plugin-core/src/main/java/appland/cli/IndexerEventUtil.java, plugin-core/src/test/java/appland/cli/IndexerEventUtilTest.java
Resolves the issue reported at https://github.com/getappmap/appmap-intellij-plugin/pull/417#pullrequestreview-1632257758
Multiple rounds of replacements create ambiguities, we're now iterating the string only once and remember if the last char was escaped or not.
=> Properly unescape indexer file paths

plugin-core/src/main/java/appland/index/AppMapMetadata.java, plugin-core/src/main/java/appland/index/AppMapMetadataService.java, plugin-core/src/main/java/appland/index/AppMapNameIndex.java, plugin-core/src/main/java/appland/index/BasicAppMapMetadata.java, plugin-core/src/main/java/appland/index/BasicAppMapMetadataExternalizer.java, plugin-core/src/main/java/appland/index/IndexUtil.java, plugin-core/src/main/java/appland/toolwindow/AppMapToolWindowFactory.java, plugin-core/src/main/java/appland/toolwindow/appmap/AppMapModel.java, plugin-core/src/main/java/appland/toolwindow/appmap/AppMapWindowPanel.java, plugin-core/src/main/java/appland/toolwindow/appmap/nodes/AppMapGroupNode.java, plugin-core/src/main/java/appland/toolwindow/appmap/nodes/AppMapNode.java, plugin-core/src/main/java/appland/toolwindow/appmap/nodes/Node.java, plugin-core/src/main/java/appland/toolwindow/appmap/nodes/ProjectNode.java, plugin-core/src/main/java/appland/toolwindow/appmap/nodes/RootNode.java, plugin-core/src/main/java/appland/toolwindow/runtimeAnalysis/nodes/RootNode.java, plugin-core/src/main/java/appland/utils/AppMapProjectUtil.java, plugin-core/src/test/java/appland/toolwindow/appmap/AppMapModelTest.java, plugin-core/src/test/java/appland/toolwindow/runtimeAnalysis/RuntimeAnalysisModelTest.java, plugin-core/src/test/java/appland/utils/ModelTestUtil.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/421
AppMaps are now displayed in a hierarchy:
- `<module name>`
- `<recorder type> (<language name> + <recorder name>`)
- `<AppMap name>`
- The tree hierarchy is expanded by default 
- The indexed data of AppMaps had to be enhanced to provide the data needed to group AppMaps
- Adds unit tests for empty AppMaps, AppMaps in one module and AppMaps in two modules of a project
=> Display AppMap hierarchy

plugin-core/src/main/java/appland/index/AppMapSearchScopes.java, plugin-java/src/main/java/appland/execution/AppMapJavaPackageConfig.java, plugin-java/src/main/java/appland/execution/AppMapPatcherUtil.java, plugin-java/src/test/java/appland/execution/AppMapJavaPackageConfigTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/385
The appmap.yml wasn't properly located if the executed run configuration defined its own search scope.
The test was updated to make the previous implementation fail as  expected.
Now, the search scope is just the content search scope of the module.
=> Don't override properties of an existing appmap.yml file

build.gradle.kts, gradle.properties
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/456
Adds compatibility to the new EAP and removes unused build properties.
The build dependency on the properties plugin is added because of https://youtrack.jetbrains.com/issue/IDEA-333586/Exception-Trying-to-add-extensions-to-non-registered-file-type-Properties-Plugin-com.intellij.java-in-tests
=> Support 2023.3 eap

plugin-core/src/main/java/appland/problemsView/FindingsManager.java, plugin-core/src/main/java/appland/problemsView/FindingsUtil.java, plugin-core/src/main/java/appland/problemsView/model/FindingsFileData.java, plugin-core/src/main/java/appland/problemsView/model/ScannerFinding.java, plugin-core/src/main/java/appland/toolwindow/runtimeAnalysis/nodes/FindingLocationNode.java, plugin-core/src/main/java/appland/webviews/appMap/AppMapFileEditorState.java, plugin-core/src/main/java/appland/webviews/findingDetails/FindingDetailsEditor.java, plugin-core/src/main/java/appland/webviews/findingDetails/FindingDetailsEditorProvider.java, plugin-core/src/main/java/appland/webviews/findings/FindingsOverviewEditor.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/407
- Keep the source finding hash in the finding details editor
- Use this hash to create the editor state for the new AppMap webview
- Use the new state to center the newly opened AppMap editor on the source finding
(@ahtrotta Why wasn't the fragment changed, which is passed from finding webview to the webview host? I think this would have changed the behavior in both VSCode and JetBrains without changes to the plugins)
This PR  needs manual testing to verify the navigation
=> Center AppMap webview on finding

plugin-core/src/main/java/appland/files/DeleteAppMapIndexDataFileListener.java, plugin-core/src/main/java/appland/toolwindow/appmap/AppMapWindowPanel.java, plugin-core/src/main/java/appland/toolwindow/appmap/DeleteAllMapsAction.java, plugin-core/src/main/java/appland/toolwindow/appmap/nodes/AppMapGroupNode.java, plugin-core/src/main/java/appland/toolwindow/appmap/nodes/Node.java, plugin-core/src/main/java/appland/toolwindow/appmap/nodes/ProjectNode.java, plugin-core/src/main/java/appland/toolwindow/appmap/nodes/RootNode.java, plugin-core/src/main/resources/META-INF/appmap-core.xml, plugin-core/src/main/resources/messages/appland.properties, plugin-core/src/test/java/appland/files/DeleteAppMapIndexDataFileListenerTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/465
This PR
- adds a context menu to the AppMap panel in the AppMap toolwindow
- Action "Delete selected AppMaps...", relying on the SDK's delete implementation for one or multiple files
- Action "Delete all AppMaps...", relying on the SDK's delete implementation for one or multiple files
- Action "Jump to source", reusing the implementation of the SDK
- Action "Expand All", reusing the implementation of the SDK
- Action "Collapse AlL", reusing the implementation of the SDK
This isn't testable in a good way, because
- we're reusing Actions of the SDK (which hopefully have test coverage already)
- the Actions interact with the user using UI dialogs. Tests are run in a headless environment and can't use dialogs
=> Support "Delete AppMaps" and "Delete all AppMaps" in the AppMap toolwindow

build.gradle.kts, gradle.properties, plugin-core/src/main/java/appland/remote/DefaultRemoteRecordingService.java, plugin-core/src/test/java/appland/WithoutAppMapAgent.java, plugin-core/src/test/java/appland/remote/DefaultRemoteRecordingServiceTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/477
This streams the AppMap JSON of the remote recording to a temporary file, then updates the `metadata.name` property of this file and then moves it to the final file, which has a `.appmap.json` extension.
This PR re-enables test `appland.remote.DefaultRemoteRecordingServiceTest` to cover the remote recording implementation. Previously, it was disabled due to incompatibility with an active AppMap agent.
=> Update name of remote recording before allowing the AppMap indexer to index it

plugin-core/src/main/java/appland/toolwindow/appmap/AppMapWindowPanel.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/490
Fixes exceptions on newer SDKs. It seems like the slow data provider is only queried if the fast provider does not provide a result.
This PR is always returning `null` when `PsiFile` is requested to enforce this.
I've tested this manually with 2021.3 and 2023.2.
=> Enforce that PsiFile is fetched with a slow/background data provider

plugin-core/src/main/java/appland/index/AppMapFindingsUtil.java, plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java, plugin-core/src/main/java/appland/installGuide/InstallGuideEditorProvider.java, plugin-core/src/main/java/appland/installGuide/projectData/DefaultProjectDataService.java, plugin-core/src/main/java/appland/installGuide/projectData/ProjectDataService.java, plugin-core/src/main/java/appland/toolwindow/installGuide/InstallGuidePanel.java, plugin-core/src/test/java/appland/installGuide/VSCodeFixturesTest.java, plugin-core/src/test/java/appland/installGuide/projectData/DefaultProjectDataServiceTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/396
This PR updates the status check of the "Runtime Analysis" step.
Setting "investigated findings" is now only set to `true` if it originates from user action in the webview and happens after the user opened an AppMap in the current project.
The VSCode plugin scopes the "user navigates to Runtime Analysis" to workspace folders, but we can't do this because there's just one panel per project. It was discussed and decided to just keep a flag per project.
Because the updated check requires read access in a background thread, I refactored the update to use a single (non-blocking) ReadAction in a background thread instead of up to four different ReadActions for a single update of the four items. This is now a clearer flow and …
=> Better determination of when Runtime Analysis is marked as complete

plugin-core/src/main/java/appland/index/AppMapFilesIterator.java, plugin-core/src/main/java/appland/index/AppMapIndexableFilesContributor.java, plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java, plugin-core/src/main/java/appland/notifications/AppMapFullContentNotification.java, plugin-core/src/main/java/appland/notifications/AppMapNotifications.java, plugin-core/src/main/java/appland/startup/DynamicPluginListener.java, plugin-core/src/main/java/appland/startup/FirstAppMapLaunchStartupActivity.java, plugin-core/src/main/java/appland/toolwindow/appmap/DeleteAllMapsAction.java, plugin-core/src/main/java/appland/upload/AppMapUploader.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/492
Replaces usage of all `@Internal` API with an alternative. We're not using internal API anymore.
This PR also drops use of API which was deprecated in 2021.3, which is the earliest supported version.
The changes to drop internal API from AppMapFilesIterator have the side-effect that we're not supporting symlinked appmap directories anymore. I don't think that it's used at all and `build/appmap` and `target/appmap` are never symlinks by default.
=> Remove usage of internal API

plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/main/java/appland/cli/LoggingProcessAdapter.java, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/411
This PR implements restart of AppMap CLI processes.
Initially, when processes are launched for an AppMap-enabled directory, both indexer and scanner processes are started.
Now, when one of the processes terminates unexpectedly, this process is restarted after a delay. The initial delay is `5s`, the next next `5s*1.5=7.25s` and the next `7.25s*1.5=10.9s` and after the third unexpected termination no further restart is attempted.
This PR adds a tests to verify the restart.
=> Restart AppMap process when it terminates unexpectedly

plugin-core/src/main/java/appland/index/AppMapIndexedRootsSetContributor.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/503
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/507
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/509
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/510
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/511
This PR fixes the required read accerss. It's unclear if the SDK is supposed to handle this or not, but we're safe-guarding it now to work with the changed behavior of 2023.3
=> Fix exception 'Read access is allowed from inside read-action' with 2023.3

plugin-core/src/main/java/appland/AppMapPlugin.java, plugin-core/src/main/java/appland/notifications/AppMapNotifications.java, plugin-core/src/main/java/appland/oauth/AppMapKeyRemoteValidator.java, plugin-core/src/main/java/appland/oauth/AppMapLocalKeyValidator.java, plugin-core/src/main/java/appland/oauth/AppMapLoginByKeyAction.java, plugin-core/src/main/resources/META-INF/appmap-core.xml, plugin-core/src/main/resources/messages/appland.properties, plugin-core/src/test/java/appland/oauth/AppMapKeyRemoteValidatorTest.java, plugin-core/src/test/java/appland/oauth/AppMapLocalKeyValidatorTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/506
This PR adds a new action to manually sign into AppMap.
When the license key is modified in the text input box, a quick local validation is performed. It verifies that the base64-decoded key matches `user@host.com:a-license-id`. After confirming the dialog the key is validated with the remote AppLand host. 
The local validation is needed because the input dialog expects it to return quickly. The remote validation is not guaranteed to return quickly because it performing a remote HTTP request.
This PR adds tests. Testing remote validation is only possible with an invalid key because we can't store valid keys in git.
Initial view of input dialog:
With invalid key:
After validation with the remote endpoint:
Notification …
=> Action to sign in with a text API key

gradle.properties
This updates the build to run the JetBrains plugin verifier against the final 2023.3 release.
gradle.properties has been updated to refer to the release version, as well. This is most useful during development, e.g. when testing against a later version than the default.
=> Build and test against 2023.3 release

build.gradle.kts
Our tests are executed with the AppMap Java agent attached.
By default, the agent is creating log files in the working directory, which is the project directory in our case.
We're now enforcing that logs are written into the build directory.
=> Don't pollute project dir with log files of the AppMap Java agent

plugin-core/src/main/java/appland/AppMapPlugin.java, plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java, plugin-core/src/main/java/appland/toolwindow/signInView/SignInViewPanel.java, plugin-core/src/main/java/appland/webviews/WebviewEditor.java, plugin-core/src/main/java/appland/webviews/appMap/AppMapFileEditor.java, plugin-core/src/main/java/appland/webviews/findingDetails/FindingDetailsEditor.java, plugin-core/src/main/java/appland/webviews/findings/FindingsOverviewEditor.java, plugin-core/src/main/java/appland/webviews/webserver/AppMapWebview.java, plugin-core/src/main/java/appland/webviews/webserver/AppMapWebviewRequestHandler.java, plugin-core/src/main/resources/META-INF/appmap-core.xml, plugin-core/src/test/java/appland/AppMapPluginTest.java, plugin-core/src/test/java/appland/webviews/webserver/AppMapWebviewTest.java
Preparation for https://github.com/getappmap/appmap-intellij-plugin/issues/533
Webviews, which interact with http:// or https:// urls, can't be served from a local `file://` URL because it would be incapable of sending preflight requests with a valid `origin` request header. A JCEF webview has to be served from a http:// URLs to support this.
This PR refactors the webview URL handling and also adds tests to ensure that the IDE's built-in webserver is properly serving the index.html files of all our webviews.
=> Serve webview files with built-in HTTP server

plugin-core/src/main/java/appland/installGuide/InstallGuideEditorProvider.java, plugin-core/src/main/java/appland/webviews/WebviewEditorIconProvider.java, plugin-core/src/main/java/appland/webviews/WebviewEditorProvider.java, plugin-core/src/main/java/appland/webviews/findingDetails/FindingDetailsEditorProvider.java
Preparation for https://github.com/getappmap/appmap-intellij-plugin/issues/533
Prepares for the Navie webview and cleans up a long-standing issue, that we were not fully implementing a WebViewEditorProvider for our Install Guide.
The code to focus on an already open, compatbiel webview editor is now reused in a better way.
=> Refactor to control reuse of opened webview editors

plugin-core/src/main/java/appland/webviews/WebviewEditor.java, plugin-core/src/main/resources/META-INF/appmap-core.xml
This helps during development to quickly locate errors or warnings in our webviews. It's disabled by default.
To enable webviews:
- `Help > Find Action... > Registry`
- Type "appmap"
- Enable option `appmap.webview.open.dev.tools`
- The developer console is now automatically shown when you open a new AppMap webview
=> Registry key to open webview console

plugin-core/src/main/java/appland/cli/AppLandCommandLineListener.java, plugin-core/src/main/java/appland/cli/AppLandCommandLineService.java, plugin-core/src/main/java/appland/cli/AppLandIndexerJsonRpcListener.java, plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java
Part of https://github.com/getappmap/appmap-intellij-plugin/issues/533
This PR updates the command line service to add `--port 0` for the indexer command and updates a new property with the port retrieved from the indexer's STDOUT.
An existing AppMap API key is passed as environment variable to both indexer and scanner.
=> Enable JSON-RPC of AppMap indexer and pass API key

plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java, plugin-core/src/main/java/appland/toolwindow/signInView/SignInViewPanel.java, plugin-core/src/main/java/appland/webviews/OpenExternalLinksHandler.java, plugin-core/src/main/java/appland/webviews/WebviewEditor.java, plugin-core/src/main/java/appland/webviews/webserver/AppMapWebview.java, plugin-core/src/main/java/appland/webviews/webserver/WebviewAuthTokenRequestHandler.java, plugin-core/src/test/java/appland/webviews/OpenExternalLinksHandlerTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/549
A recent changed made use of the IDE's built-in webserver to server html and css for our webviews.
More recent versions of the IDEs validate requests and reject requests, which don't have an auth token query parameter and which don't have the a project name in the path. 
We're now hooking into the webview to enrich requests to our http://localhost:.../ AppMap urls with an auth token.
The alternative would be to launch and manage our own, built-in HTTP server to server webview assets.
=> Add auth token to AppMap webview requests

plugin-core/src/main/java/appland/toolwindow/appmap/nodes/RootNode.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/541
- Fixes a NullPointerException I got when testing the plugin
- Fixes the exception about slow operations when loading AppMaps. It must have been thrown when status of the "Delete All AppMaps" action is updated. I was unable to reproduce, though. But the stacktrace was clear enough.
- Fixes a minor issue with nested ReadActions.
I don't think that manual QA testing is needed for this. @ahtrotta it would be great if you tested this on your machine.
=> Improve loading of AppMaps in AppMap tool window

gradle.properties
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/535
This adds compatibility with 2024.1 eap. Compilation did not show problems and all tests passed.
I'm waiting for 2024.1 eap3 to be fully published before making this PR available for review.
=> Support JetBrains 2024.1 EAP releases

plugin-core/src/main/resources/messages/appland.properties, plugin-gradle/src/main/java/appland/execution/AppMapGradleAgentRunner.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/566
The issue contains instructions how to reproduce.
The retrieval of the Gradle JDK became a "slow operation" in 2023.2 and we must not fetch it on the UI dispatch thread (i.e. the EDT).
=> Retrieve Gradle JDK in a background thread

plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/586
This fixes the deadlock I noticed while testing "Explain with Navie".
A background thread locked the active AppMap dirs and waited for indexing to complete, but the "Explain with Navie" action attempted to access the same information under a lock. This froze the UI thread while indexing was still in progress.
=> Possible freeze of UI if "Explain with Navie" is invoked during indexing

plugin-core/src/main/java/appland/webviews/webserver/AppMapWebviewRequestHandler.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/579
The preview JetBrains Markdown is opening URLs, which don't work with `path()`.
Our request handler is only suitable for our own URLs, so we can safely skip URLs we're unable to parse.
=> Exception "java.lang.IllegalArgumentException: invalid hex byte"

plugin-core/src/main/java/appland/cli/AppLandCommandLineService.java, plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/test/java/appland/AppMapBaseTest.java, plugin-java/src/test/java/appland/execution/BaseAppMapJavaTest.java
This fixes our flaky tests on the Windows runner of GitHub Actions.
The problem was an incorrect shutdown or the AppLand processes launched by tests. The first shutdown attempt cleared the processes and only waited for 1.0s, which isn't enough for slow Windows CI. The next shutdown attempts only got the empty list of processes and stopped early.
This PR updates the shutdown timeout to 10s and passes it into the service implementation handling the shutdown instead of attempting to be clever with several (incorrect) attempts.
=> Fix flaky Windows CI

plugin-core/src/main/java/appland/webviews/navie/NavieEditorProvider.java, plugin-core/src/main/resources/messages/appland.properties
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/571
If the current IDE's webview JCEF isn't suitable for Navie, then show a notification to ask the user to update. If the user chose "don't show again", then the message is never shown again in any of the user's projects.
We're showing the message on top of the Navie editor tab, but because JCEF rendering is async the message is shown before the webview is fully visible.
If this is a problem, we could inject the message more deeply into the editor, e.g. when the webview's message that it's ready is received.
=> Notify user if Navie isn't fully functional

plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java
CI failed on `develop`: https://github.com/getappmap/appmap-intellij-plugin/actions/runs/8116975781/job/22188160161
This PR is extending the timeout for process shutdown in our tests. It's using the new method added by #594
=> Wait longer for AppMap process shutdown in Windows tests

plugin-core/src/main/java/appland/oauth/AppMapOAuthRequestHandler.java
2024.1 is breaking the API we're using for "Sign in to AppMap" in an incompatible way. I've reported this at https://youtrack.jetbrains.com/issue/IDEA-346395, but so far JetBrains doesn't seem likely to fix this.
This PR is fixing the problem on our side to allow users of 2024.1 to sign in to AppMap.
This can be tested by using the "Sign in" action (at `Tools > AppMap`) with the current 2024.1 eap of a JetBrains IDE. It should also be tested with 2022.1, our earliest supported version.
I've successfully tested this with both versions.
=> Fix compatibility with 2024.1 eap's backwards incompatible API of OAuthRequestHandlerBase

.github/workflows/webview-update.yml, appland-findings/package.json, appland-install-guide/package.json, appland-signin/package.json
Updates the new CI workflow added with #604 to only update one webview at a time and to use a unique branch per webview.
Dropping the two remaining ` "packageManager": "yarn@2.4.2"` from package.json was necessary because NPM/node available with the `ubuntu-latest` runner was complaining about incompatible settings (see https://github.com/getappmap/appmap-intellij-plugin/actions/runs/8231132338/job/22505835614#step:5:7).
Sample pull request:
- https://github.com/getappmap/appmap-intellij-plugin/pull/610 . This also includes the changes of this PR because I had to execute the CI workflow from this branch.
=> Update new CI workflow to create webview pull requests

build.gradle.kts, gradle.properties
In other PRs the build was failing due to the plugin verifier reports.
By default, the build setup uses the latest version of the plugin verifier. Today a new version was released, which incorrectly flags our code.
I've reported this at
https://youtrack.jetbrains.com/issue/MP-6438/Plugin-verifier-1.365-incorrectly-flags-overridden-methods-of-OverrideOnly
This PR uses the previous version of the plugin verifier to make our build work again.
=> Fix GitHub Actions

build.gradle.kts, plugin-core/src/main/java/appland/AppMapPlugin.java, plugin-core/src/main/resources/messages/appland.properties, plugin-core/src/test/java/appland/AppMapPluginTest.java, plugin-java/src/main/java/appland/execution/AppMapJvmCommandLinePatcher.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/624
Our Gradle setup was already downloading the latest version to run the tests with the AppMap Java agent.
We're reusing this to bundle the downloaded agent jar into the plugin.zip.
The bundled files is used as a fallback if the download of the remote agent JAR failed.
=> Bundle the AppMap Java agent with plugin

build.gradle.kts, plugin-core/src/main/java/appland/cli/CliTool.java, plugin-core/src/main/java/appland/cli/DefaultAppLandDownloadService.java, plugin-core/src/test/java/appland/cli/AppLandDownloadServiceTestUtil.java, plugin-core/src/test/java/appland/cli/CliToolTest.java, plugin-core/src/test/java/appland/cli/DefaultAppLandDownloadServiceProxyTest.java, plugin-core/src/test/java/appland/cli/DefaultAppLandDownloadServiceTest.java, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java, plugin-core/src/test/java/appland/testRules/MockServerSettingsRule.java, plugin-core/src/test/java/appland/testRules/OverrideIdeHttpProxyRule.java, plugin-java/src/test/java/appland/javaAgent/AppMapJavaAgentDownloadServiceProxyTest.java, plugin-java/src/test/java/appland/javaAgent/AppMapJavaAgentDownloadServiceTest.java, plugin-java/src/test/java/appland/javaAgent/OverrideJavaAgentLocationRule.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/621
Tests downloads of AppMap binaries and of the Java agent JAR.
The only change (except the new tests) is a change to the AppMap CLI URLs to unescape unnecessarily escaped `@` and `/` characters of the URL to make it work with the Mockserver.
=> Tests to make sure that downloads use the IDE's proxy

plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/main/java/appland/settings/AppMapApplicationSettings.java, plugin-core/src/main/kotlin/appland/settings/AppMapProjectSettingsPanel.kt, plugin-core/src/main/resources/messages/appland.properties, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java
Fixes #646
Followups:
- documentation,
- restart services on config change,
- use credential storage for OpenAI key.
=> feat: Allow configuring environment for AppMap services

plugin-core/src/main/java/appland/execution/ProgramParameterUtils.java, plugin-java/src/main/java/appland/execution/AppMapPatcherUtil.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/546
Previously, the file was created in the guessed project base directory, which doesn't always match the project root of a Gradle project
Previously, with the setup below and when executing `test` in Gradle sub-module `junit5/platform-tests`, `appmap.yml`  was created in `multi-module-setup/project-files` and not in `multi-module-setup/junit5`.
This PR fixes this by  looking at the "external project path" of Gradle run configurations. It's used as a fallback if there's not more specific working directory specified in the run configuration.
Run this:
```
mkdir multi-module-setup
cd multi-module-setup
mkdir project-files
git clone https://github.com/junit-team/junit5.git
git clone …
```
=> Create appmap.yml in the correct directory when used with Gradle

plugin-core/src/main/java/appland/files/AppMapFiles.java, plugin-core/src/main/resources/META-INF/appmap-core.xml, plugin-core/src/test/java/appland/AppMapBaseTest.java, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java, plugin-core/src/test/java/appland/index/AppMapSearchScopesTest.java, plugin-core/src/test/java/appland/problemsView/listener/ScannerFilesAsyncListenerContentRootTest.java, plugin-core/src/test/java/appland/toolwindow/appmap/AppMapModelTest.java, plugin-core/src/test/java/appland/utils/ModuleTestUtils.java, plugin-java/src/main/java/appland/execution/AppMapJavaAgentRunner.java, plugin-java/src/main/java/appland/execution/AppMapJavaPackageConfig.java, plugin-java/src/main/java/appland/execution/AppMapJvmCommandLinePatcher.java, plugin-java/src/main/java/appland/execution/AppMapPatcherUtil.java, plugin-java/src/main/java/appland/execution/AppMapProgramPatcher.java, plugin-java/src/test/java/appland/execution/AppMapJavaPackageConfigHeavyTest.java, plugin-java/src/test/java/appland/execution/AppMapJavaPackageConfigTest.java, plugin-maven/src/main/java/appland/execution/AppMapMavenProgramPatcher.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/659
This PR is based on https://github.com/getappmap/appmap-intellij-plugin/pull/661, which must be merged first.
This PR improves the support for projects with multiple modules.
Sample project structure:
- `/project`: Root directory of the project and content root of a module
- `/project/appmap.yml`: Existing AppMap config file
- `/project/submodule`: Content root of module `submodule`
Starting (maven) tests inside `submodule`:
Without this PR, a new config file was created at `/project/submodule/appmap.yml` instead of reusing the existing `/project/appmap.yml` file.
This PR fixes the search so that the top-level `appmap.yml` file is used instead and no new appmap configuration file is created. 
Only directories, which are …
=> Improve support for multi-module Maven projects

plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java, plugin-core/src/test/java/appland/utils/ModuleTestUtils.java
When I was debugging https://github.com/getappmap/appmap-intellij-plugin/issues/597 I noticed that processes were left running. This happened when I closed and reopened a project quickly.
Terminating AppMap processes takes a few seconds on this system. If there's already a new process for an AppMap directory when a process terminates and calls its termination listener, then the reference to the new process was removed and it was left running.
This is now fixed by this PR.
After the change CI become even more unstable. I've patched a few problems of process termination and the test setup code. This PR is required for https://github.com/getappmap/appmap-intellij-plugin/pull/679, because in that PR "Reopen project" is triggering the bug fixed by this PR.
=> Do not remove the process reference if it's not the terminated process

plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/main/java/appland/notifications/AppMapNotifications.java, plugin-core/src/main/java/appland/rpcService/DefaultAppLandJsonRpcService.java, plugin-core/src/main/java/appland/settings/AppMapApplicationSettings.java, plugin-core/src/main/java/appland/settings/AppMapProjectConfigurable.java, plugin-core/src/main/java/appland/settings/AppMapSecureApplicationSettings.java, plugin-core/src/main/java/appland/settings/AppMapSecureApplicationSettingsService.java, plugin-core/src/main/java/appland/settings/AppMapSettingsListener.java, plugin-core/src/main/java/appland/settings/OpenAIReloadProjectListener.java, plugin-core/src/main/kotlin/appland/settings/AppMapProjectSettingsPanel.kt, plugin-core/src/main/resources/META-INF/appmap-core.xml, plugin-core/src/main/resources/messages/appland.properties
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/675
This PR adds a new setting to configure a custom OpenAI key.
There's currently no additonal action (e.g. `AppMap: Set OpenAPI key`), but it could be added if it's needed.
Settings are persisted in the IDE's password safe.
When the OpenAI key changed, a notification is displayed in each open project to allow the user to reload it. 
The application-wide JSON-RPC process **is NOT restarted** immediately after the change of the OpenAI key. A restart would invalidate the port used by open Navie webviews.
The notification is sticky, which means that it won't hide automatically. Otherwise the user might miss the required reload.
This PR is moving `applyServiceEnvironment` from the application settings class to the command line …
=> Allow users to specify their own OpenAI key in the settings

plugin-core/src/main/java/appland/rpcService/AppLandJsonRpcListener.java, plugin-core/src/main/java/appland/rpcService/AppLandJsonRpcListenerAdapter.java, plugin-core/src/main/java/appland/rpcService/DefaultAppLandJsonRpcService.java, plugin-core/src/main/java/appland/rpcService/SetConfigurationV1Params.java, plugin-core/src/main/java/appland/rpcService/SetConfigurationV2Params.java, plugin-core/src/test/java/appland/rpcService/DefaultAppLandJsonRpcServiceTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/667
This PR implements JSON-RPC message `v2.configuration.set`. 
It send the project's content roots as property `projectDirectories`. Nested content roots are removed from the list sent to the JSON-RPC service.
For spring-petclinic the following message is generated:
```json
{
"jsonrpc": "2.0",
"method": "v2.configuration.set",
"params": {
"projectDirectories": [
"/sources/spring-petclinic-2023-08-31"
],
"appmapConfigFiles": [
"/sources/spring-petclinic-2023-08-31/appmap.yml"
]
}
}
```
Only appmap-analysis is failing on CI, I don't know what's causing this failure.
=> Send project content roots to local AppLand JSON-RPC service

.github/workflows/build.yml, plugin-core/src/main/java/appland/config/AppMapConfigFile.java, plugin-core/src/test/java/appland/config/AppMapConfigFileTest.java
When generating the default config file, set the language property.
Fixes #689 .
=> fix: set language property in default config

plugin-core/src/main/java/appland/toolwindow/navie/NaviePanel.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/688
Previously, the text selection was only used if Navie was opened via `Tools > AppMap > Explain with Navie`.
With this PR, opening Navie with the blue button is now using the selected text, too.
=> Provide selection of current editor to Navie if it's opened from the AppMap tool window

plugin-core/src/main/java/appland/rpcService/DefaultAppLandJsonRpcService.java, plugin-core/src/test/java/appland/rpcService/DefaultAppLandJsonRpcServiceTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/708
Passes environment variable "APPMAP_CODE_EDITOR" to the Navie JSON-RPC process.
For simplicity and compatibility, we're currently using the SDK's built-in application info strings.
For IntelliJ Community, the value is "IntelliJ IDEA 2023.2 by JetBrains s.r.o.".
This should work well for products like WebStorm or Google's Android Studio.
=> Pass code editor to Navie JSON-RPC server

plugin-core/src/main/java/appland/cli/DefaultAppLandDownloadService.java, plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java, plugin-core/src/test/java/appland/testRules/ResetIdeHttpProxyRule.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/700
With this PR, the IDE's HTTP proxy settings are passed as environment variables to all AppMap CLI processes launched by the plugin. This include the JSON-RPC server, scanner and indexer.
The following variables are added to the environment of AppMap processes, but only if HTTP proxy settings of the IDE are enabled:
- `http_proxy`
- `https_proxy` 
- `no_proxy` 
If the IDE configured username and password for proxy authentication, then both are included in the proxy URL values, e.g. `http://myUser:secure_password@my.proxy:1234`.
I'm not aware of a way to listen to changes of the IDE's proxy settings.
For unknown reasons the download tests started to fail, https://github.com/getappmap/appmap-intellij-plugin/pull/703/commits …
=> Pass IDE proxy settings to the AppMap CLI tools

plugin-core/src/main/java/appland/webviews/navie/NavieEditor.java, plugin-core/src/main/java/appland/webviews/navie/NavieEditorProvider.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/695
The most recent AppMaps were already supposed to be updated, but a bug prevented that (the update code still assumed that there's an AppMap directory).
This PR fixes the bug and also adds that Navie's property `appmapYmlPresent` is updated when there's a change to `appmap.yml` in the project.
=> Update an opened Navie view when appmap.yml or new AppMap are created

plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/725
This fixes a `NullPointerException` when a HTTP proxy server is enabled but not host exceptions are defined.
It adds a test to verify that the proxy environment is properly created for a `null` value of proxy exclusions.
=> NPE with 2024.1 if a proxy server without exceptions is set

plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/main/java/appland/rpcService/DefaultAppLandJsonRpcService.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/706
On Windows 10 or later, newer IDEs attempt to terminate processes via ctrl+c at first. The AppMap JSON-RPC server did not terminate within 5s and a timeout exception was thrown. We're now catching it to fallback to forced process termination.
=> Handle timeout when terminating processes on Windows

plugin-core/src/main/java/appland/notifications/AppMapNotifications.java, plugin-core/src/main/java/appland/settings/AppMapApplicationSettings.java, plugin-core/src/main/java/appland/toolwindow/AppMapToolWindowFactory.java, plugin-core/src/main/java/appland/webviews/WebviewEditor.java, plugin-core/src/main/resources/messages/appland.properties
This PR displays a message about broken proxy support for users
- using 2024.1.x
- with an enabled HTTP proxy server
- which did not click "Don't show again" when the same message was displayed earlier
"Don't show again" deactivates the message for all projects.
=> Show warning for users of 2024.1 with proxy servers

description.md, gradle.properties, plugin-core/src/main/java/appland/index/AppMapIndexableFilesContributor.java, plugin-core/src/main/java/appland/webviews/navie/NavieEditorProvider.java, plugin-core/src/main/resources/META-INF/appmap-core.xml, plugin-core/src/main/resources/messages/appland.properties, plugin-core/src/test/java/appland/index/AppMapIndexableFilesContributorTest.java, plugin-core/src/test/java/appland/index/AppMapIndexedRootsSetContributorTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/728
Reverts changes which were made to drop support for older major versions.
This PR reverts selected changes of the following commits:
- b2279455f8b039ba0ddb1b53fb4580dde17ed7a5
- 4c756aad28bbdfec52c03349df71d228a9ad4785
- 74bbaa816e74b88e459952ae0a7d5d956c5c2600
This also restores the warning about broken text input shown when a Linux user opens Navie.
=> Restore compatibility with 2023.1

.github/workflows/build.yml, .github/workflows/deploy.yml, .gitignore, build.gradle.kts, gradle.properties, plugin-core/src/main/java/appland/cli/AppLandProjectOpenActivity.java, plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/main/java/appland/config/AppMapConfigFile.java, plugin-core/src/main/java/appland/index/AppMapIndexableFilesContributor.java, plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java, plugin-core/src/main/java/appland/toolwindow/appmap/DeleteAllMapsAction.java, plugin-core/src/main/java/appland/utils/DataContexts.java, plugin-core/src/main/java/appland/webviews/navie/NavieEditorProvider.java, plugin-core/src/test/java/appland/AppMapBaseTest.java, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java, plugin-core/src/test/java/appland/index/AppMapIndexableFilesContributorTest.java, plugin-core/src/test/java/appland/index/AppMapIndexedRootsSetContributorTest.java, plugin-core/src/test/java/appland/index/AppMapSearchScopesTest.java, plugin-core/src/test/java/appland/index/ClassMapTypeIndexTest.java, plugin-core/src/test/java/appland/problemsView/FindingsManagerTest.java, plugin-core/src/test/java/appland/problemsView/listener/ScannerFilesAsyncListenerContentRootTest.java, plugin-core/src/test/java/appland/rpcService/DefaultAppLandJsonRpcServiceTest.java, plugin-core/src/test/java/appland/toolwindow/appmap/AppMapModelTest.java, plugin-core/src/test/java/appland/utils/IndexTestUtils.java, plugin-core/src/test/java/appland/utils/ModuleTestUtils.java, plugin-java/src/test/java/appland/execution/AppMapJavaPackageConfigTest.java, plugin-java/src/test/java/appland/execution/BaseAppMapJavaTest.java, settings.gradle.kts
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/717
Adds compatibility with 2024.2 eap.
This time, supporting the new EAP is a bit painful. It requires a new Gradle build setup (using a beta version of a new Gradle plugin) and JetBrains clarified the internal API in the new major version.
- Because 2024.2 requires a new build setup, this PR is migrating to the new Gradle build setup.
- CI is now using Java 21, because 2024.2 migrated from Java 17 to 21
- Indexing is now async in tests with 2024.2. We're changing our tests to wait until indexing finished because we rely on indexes.
- In the build setup, we're working around a few problems of the new intellij-platform-gradle plugin, we'll remove them as soon as the plugin is fixed
=> Support 2024.2 eap

build.gradle.kts, gradle.properties
The SDK made API internal without a replacement. Until this is hopefully solved with one of the next eap releases, we're dropping compatibility with 2024.2 to pass the release review process.
=> Temporarily drop compatibility with 2024.2

gradle.properties, plugin-core/src/main/java/appland/actions/GenerateOpenApiAction.java, plugin-core/src/main/java/appland/actions/OpenInRightSplit.java, plugin-core/src/main/java/appland/webviews/SharedAppMapWebViewMessages.java, plugin-core/src/test/java/appland/rpcService/DefaultAppLandJsonRpcServiceTest.java
2024.2 made this API internal without a replacement, despite use in published plugins.
This has been reported to JetBrains YouTrack  at https://youtrack.jetbrains.com/issue/IJPL-158380
"Generate OpenAPI" does not open a split mode anymore, so this use of the split action was removed.
This PR also updates to the latest beta of 2024.2 to make sure that the plugin verifier is running with a version which already contains the API change.
This change can be tested by navigating to a source file from the AppMap webview.
I've tested this on 2023.1 and 2024.2 eap.
=> Work around internal API of 2024.2 `OpenInRightSplitSplit`

.gitattributes, appland-navie/package.json, appland-navie/webview.js, appland-navie/yarn.lock, plugin-core/src/main/java/appland/webviews/navie/NavieEditor.java
Instead of destructively clearing the current chat, "new chat" button opens a new tab instead.
Requires support in @appland/components provided by https://github.com/getappmap/appmap-js/pull/1925
(Counterpart of https://github.com/getappmap/vscode-appland/pull/995 )
Please note I haven't committed recompiled dist files. They should be recompiled after the components change is merged.
Also note I haven't actually tested this (I have some issues trying to run the plugin).
=> fix: "New chat" button opens a new chat

plugin-core/src/main/java/appland/cli/AppLandProjectManagerListener.java, plugin-core/src/main/java/appland/cli/AppMapCommandLineConfigListener.java, plugin-core/src/main/java/appland/cli/DefaultCommandLineService.java, plugin-core/src/main/java/appland/rpcService/AppMapJsonRpcServerStartupActivity.java, plugin-core/src/main/java/appland/rpcService/DefaultAppLandJsonRpcService.java, plugin-core/src/main/java/appland/utils/AppMapProcessUtil.java, plugin-core/src/main/resources/META-INF/appmap-core.xml, plugin-core/src/test/java/appland/AppLandTestExecutionPolicy.java, plugin-core/src/test/java/appland/AppMapBaseTest.java, plugin-core/src/test/java/appland/cli/DefaultAppLandDownloadServiceProxyTest.java, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java, plugin-core/src/test/java/appland/javaAgent/AppMapJavaAgentDownloadServiceProxyTest.java, plugin-core/src/test/java/appland/problemsView/FindingsManagerTest.java, plugin-core/src/test/java/appland/rpcService/DefaultAppLandJsonRpcServiceTest.java
This is merging some changes of outdated PR https://github.com/getappmap/appmap-intellij-plugin/pull/674
This should make tests more reliable and easier to debug. Async process execution is disabled for tests now and this should avoid some of the unstable tests we've observed in the past.
The AppMap report is showing nicely that there this PR un-ignored two of the previously flaky tests :) 
A user-visible fix is https://github.com/getappmap/appmap-intellij-plugin/pull/762/commits/96cc6c2cfbfc7c86fb07504eba50d207e98dd310, which fixes the restart of the JSON-RPC server after too many terminations of the process.
=> Improve test setup and reenable two tests

.github/workflows/build.yml, build.gradle.kts, gradle.properties, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java, plugin-core/src/test/java/appland/toolwindow/appmap/AppMapModelTest.java, plugin-core/src/test/java/appland/toolwindow/runtimeAnalysis/RuntimeAnalysisModelTest.java, plugin-core/src/test/java/appland/utils/ModelTestUtil.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/557
CI: Only the AppMap analysis failed and I'm unable to fix it because a re-run doesn't do that.
This PR adds an additional matrix build configuration to test against the latest supported IDE major version.
To avoid unnecessarily long job runtime, we're only running tests against the latest version on Linux, for now.
The verification of the plugin structure and binary release was split off into another job to simplify the structure of the workflow.
Tests, which failed on 2024.1 but not on 2023.1, are also fixed in this PR.
=> Run tests against the latest supported major version

plugin-core/src/main/java/appland/problemsView/FindingsManager.java, plugin-core/src/main/java/appland/problemsView/listener/PendingScannerFindingsChangesService.java, plugin-core/src/main/java/appland/problemsView/listener/ScannerFilesAsyncListener.java, plugin-core/src/main/java/appland/startup/AppLandStartupActivity.java, plugin-core/src/test/java/appland/AppMapLocalTempFilesTest.java, plugin-core/src/test/java/appland/cli/DefaultCommandLineServiceTest.java, plugin-core/src/test/java/appland/problemsView/listener/ScannerFilesAsyncListenerContentRootTest.java, plugin-core/src/test/java/appland/problemsView/listener/ScannerFilesAsyncListenerTest.java, plugin-core/src/test/java/appland/toolwindow/runtimeAnalysis/RuntimeAnalysisModelTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/770
Tests of the plugin are passing, but the AppMap task is still failing for unknown reasons.
Especially with 2024.2 and GitHub Actions, the tests of the finding manager were unstable.
This was caused by too many async change requests of findings launched in the background.
The tests only wait for one of these changes and then continue to work with findings data. At this point, other queued async changes to findings could still be processed and change the findings data in unexpected ways.
This PR 
- batches changes to findings and debounces the processing. Findings are processed 5s after the last change to findings was recorded.
- avoids spawning a cancellable ReadAction to all findings from an existing ReadAction.
- When …
=> Fix unstable findings tests

plugin-core/src/main/java/appland/files/AppMapAsyncFileListener.java, plugin-core/src/main/java/appland/files/AppMapFileChangeListener.java, plugin-core/src/main/java/appland/files/AppMapFiles.java, plugin-core/src/main/java/appland/files/VirtualFileManagerLister.java, plugin-core/src/main/java/appland/index/AppMapConfigFileIndex.java, plugin-core/src/main/java/appland/index/IndexUtil.java, plugin-core/src/main/java/appland/index/IndexedFileListenerUtil.java, plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java, plugin-core/src/main/java/appland/notifications/FirstAppMapListener.java, plugin-core/src/main/java/appland/problemsView/FindingsViewTab.java, plugin-core/src/main/java/appland/telemetry/AppMapRecordListener.java, plugin-core/src/main/java/appland/toolwindow/appmap/AppMapWindowPanel.java, plugin-core/src/main/java/appland/webviews/navie/NavieEditor.java, plugin-core/src/main/resources/META-INF/appmap-core.xml, plugin-core/src/test/java/appland/files/AppMapAsyncFileListenerTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/754
- https://github.com/getappmap/appmap-intellij-plugin/pull/759/commits/dd46266f6a10f45c5dd8e6c4c9410dae2dc658cb
For Navie and other code the presence of appmap.yml files in the project is detected. We used the SDK's FilenameIndex, which should be suitable for tasks like this. But it proved to expensive to call because it attempted to update a lot of index data of files we don't care about.  This commit adds an index only for the filename indexing of appmap.yml files to make the lookup much faster and cheaper.
- https://github.com/getappmap/appmap-intellij-plugin/pull/759/commits/553decd799abb1b466d26e22fcdf8fc9a8b6c3e9 changes the handling of generic filesystem refresh events. Previously, every refresh and even a …
=> Improve performance when Navie editor is opened

plugin-core/src/main/java/appland/settings/AppMapSecureApplicationSettingsService.java, plugin-core/src/main/resources/messages/appland.properties, plugin-core/src/test/java/appland/settings/AppMapSecureApplicationSettingsServiceTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/773
In 2024.2+ the method to load a key from secure password storage is a slow operation and causes an exception.
This PR applies the changes to load the key in a background task to avoid the exception.
The key is cached in memory after it's been retrieved from secure storage to avoid the expensive call at runtime.
=> Avoid exception about slow operation when loading OpenAI key

plugin-core/src/main/java/appland/installGuide/InstallGuideEditorProvider.java, plugin-core/src/main/java/appland/webviews/WebviewEditorProvider.java, plugin-core/src/main/java/appland/webviews/findingDetails/FindingDetailsEditorProvider.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/752
When the install guide instructions are clicked, an already opened editor is now always selected and focused.
=> Focus open install guide webview editor when it's invoked from AppMap toolwindow

plugin-core/src/main/java/appland/problemsView/FindingsPanelProvider.java, plugin-core/src/main/java/appland/settings/AppMapApplicationSettings.java, plugin-core/src/main/java/appland/settings/AppMapSettingsListener.java, plugin-core/src/main/java/appland/settings/AppMapSettingsReloadProjectListener.java, plugin-core/src/main/java/appland/toolwindow/appmap/AppMapWindowPanel.java, plugin-core/src/main/kotlin/appland/settings/AppMapProjectSettingsPanel.kt, plugin-core/src/main/resources/META-INF/appmap-core.xml
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/751
This hidese the problems view panel and the Runtime Analysis panel in the AppMap toolwindow if the scanner is turned off.
When the setting is changed, a notification about a required project reload is shown.
=> Don't show AppMap problems view and the Runtime Analysis if scanner is off

plugin-core/src/main/resources/META-INF/appmap-core.xml
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/781
The AppMap should provide the default view for its own JSON files (.appmap.json).
In this case, the DataGraph plugin was overriding the default view.
=> Make the AppMap viewer the default view for .appmap.json files

.github/workflows/build.yml
This PR fixes the broken CI.
Due to a regression, the AppMaps were not uploaded on CI which caused the AppMap analysis action to fail.
=> Fix incorrect AppMap upload of CI

README.md, description.md
This PR https://github.com/getappmap/applandinc.github.io/pull/1507 Needs to be merged first to make the updated screenshots available on appmap.io since jetbrains can render webp images.
=> Update the screenshots to png as jetbrains doesn't support webp rendering

gradle.properties
This updates the verification during the build to use the latest eap of 2024.3
=> chore: run plugin verification with latest eap of 2024.3

gradle.properties, src/main/resources/META-INF/plugin.xml
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/834
I'm not sure if the Marketplace is properly evaluating the compatibility. We'll have to check the detected compatibility after a new release with this change has been uploaded.
How it's shown in Rider after manual installation:
=> Mark AppMap as incompatible with Rider

plugin-copilot/src/main/java/appland/copilotChat/ChooseCopilotModelAction.java, plugin-copilot/src/main/java/appland/copilotChat/CopilotAppMapEnvProvider.java, plugin-copilot/src/main/java/appland/copilotChat/NavieCopilotChatRequestHandler.java, plugin-copilot/src/main/java/appland/copilotChat/copilot/CopilotChatSession.java, plugin-copilot/src/main/resources/META-INF/appmap-copilot.xml, plugin-core/src/main/java/appland/settings/AppMapApplicationSettings.java, plugin-core/src/main/java/appland/settings/AppMapSettingsListener.java, plugin-core/src/main/java/appland/settings/AppMapSettingsReloadProjectListener.java, plugin-core/src/main/resources/messages/appland.properties
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/824
This PR adds a new action to choose the Copilot model for Navie.
This changes the existing "loadModels" to only return models suitable for chat, i.e. only models with `type == "chat"`.
Menu item to invoke the action:
Popup to choose the model. The model currently selected for Navie is pre-selected when the popup is shown.
=> Support to choose the copilot model for Navie

.github/workflows/build.yml, build.gradle.kts, gradle.properties, plugin-core/src/main/java/appland/actions/StopAppMapRecordingAction.java, plugin-core/src/main/java/appland/notifications/AppMapNotifications.java, settings.gradle.kts
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/837
This PR adds compatibility with the upcoming 2025.1.
To build with 2025.1 for local development, we  need to use Kotlin 2.1 instead of 1.9.x.
This PR drops an override-only violation when invoking one of our own actions.
As there's no Copilot plugin yet for 2025.1, there's a change to work without the plugin. The Copilot integration is still enabled, though.
=> Add support for 2025.1

.run/intellij-plugin [runIde].run.xml, build.gradle.kts, plugin-copilot/src/main/java/appland/copilotChat/CopilotStartupNotificationActivity.java, plugin-copilot/src/main/java/appland/copilotChat/copilot/CopilotContentExclusion.java, plugin-copilot/src/main/java/appland/copilotChat/copilot/GitHubCopilot.java, plugin-copilot/src/main/java/appland/copilotChat/copilot/GitHubCopilotService.java, plugin-copilot/src/main/java/appland/copilotChat/copilot/UpdatingCopilotToken.java, plugin-core/src/main/java/appland/notifications/AppMapNotifications.java, plugin-core/src/main/resources/messages/appland.properties
This pull request introduces several changes to enhance the Copilot plugin, including new functionality for handling content exclusions and updates to existing services and notifications.
* [`plugin-copilot/src/main/java/appland/copilotChat/copilot/CopilotContentExclusion.java`](diffhunk://#diff-f2e48992aa593951e22d2a1f51f9d70b2cc556d203efab514ae59f085dfafb08R1-R77): Added a new class to fetch and manage content exclusion rules from the Copilot API.
* [`plugin-copilot/src/main/java/appland/copilotChat/copilot/GitHubCopilot.java`](diffhunk://#diff-b2fd844a2f86c4b4539119b7150dba414faea536ec4246a18a0df6bd1639b03eR20-R21): Introduced a new constant `INTERNAL_API_URL` for the Copilot internal API.
* [`plugin-copilot/src/main/java/appland/copilotChat/copilot/GitHubCopilotService.java`](diffhunk: …
=> Download content exclusion lists from GitHub

plugin-copilot/src/main/java/appland/copilotChat/NavieCopilotChatRequestHandler.java, plugin-copilot/src/main/java/appland/copilotChat/copilot/GitHubCopilot.java, plugin-copilot/src/test/java/appland/copilotChat/copilot/CopilotModelDefinitionTest.java
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/826
The current already had `gpt-4o` as fallback model.
This PR makes a few changes to make the handling more clear and adds a test based on a snapshot of the `/models` response.
=> Improve handling of GitHub Copilot fallback model

.github/workflows/build.yml, .run/Run tests (2024.3).run.xml, .run/Run tests.run.xml, .run/runIDE 2025.1.run.xml, .run/runIde 2024.3.run.xml, .run/runIde.run.xml, build.gradle.kts, development.md, gradle-241.properties, gradle-242.properties, gradle-243.properties, gradle-251.properties, gradle.properties, plugin-core/src/main/java/appland/settings/AppMapApplicationSettings.java, plugin-core/src/main/java/appland/settings/AppMapSettingsListener.java, plugin-core/src/main/java/appland/settings/AppMapSettingsReloadProjectListener.java, plugin-java/src/main/java/appland/execution/AppMapPatcherUtil.java, settings.gradle.kts
With this PR, `gradle runIde` is working with 2025.1 eap4 and an error raised by the IDE about service initialization is fixed.
=> Improve compatibility with 2025.1 eap

plugin-copilot/src/main/java/appland/copilotChat/NavieCopilotChatRequestHandler.java, plugin-copilot/src/main/java/appland/copilotChat/copilot/CopilotChatSession.java, plugin-copilot/src/main/java/appland/copilotChat/copilot/GitHubCopilotService.java, plugin-core/src/main/java/appland/rpcService/DefaultAppLandJsonRpcService.java, plugin-core/src/main/java/appland/utils/UserLog.java
This pull request includes several improvements and error handling enhancements to the `NavieCopilotChatRequestHandler` and related classes. The key changes involve adding logging functionality, improving request handling, and updating error responses. In particular it fixes a bug where error responses were never actually sent to the client, leading to upstream errors just appearing as hanging to the client.
* [`plugin-copilot/src/main/java/appland/copilotChat/NavieCopilotChatRequestHandler.java`](diffhunk://#diff-befb6a04a2b70333c0d3a41e05d6eeb3d3a104a458ea79626e5fed8575eaf309L49-L102): Improved error handling in `process` method by adding specific responses for unauthorized access, token count limits, and internal server errors. Introduced `sendErrorResponse` method for consistent error …
=> Log requests in copilot proxy and actually send errors back to the client

build.gradle.kts, gradle-241.properties, gradle-242.properties, gradle-243.properties, gradle-251.properties
- Use the latest version of Copilot for local testing and development.
- Use the current snapshot of the intellij-platform Gradle plugin because it has important performance optimizations. Without it, local builds can be very slow.
=> Update build setup

build.gradle.kts, gradle-241.properties, gradle-242.properties, gradle-243.properties, gradle-251.properties, gradle.properties, gradle/wrapper/gradle-wrapper.properties, gradlew
Updates the build setup to use the latest available versions and to build against the current 2025.1 eap.
Updates
- 2025.1 eap version for the plugin verifier
- Gradle to 8.13
- Copilot plugin to 1.5.40, only used for testing
The intellij-platform Gradle plugin could not be updated due to https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1913
=> Verify against latest 2025.1, update build setup

.github/workflows/build.yml, build.gradle.kts, gradle-241.properties, gradle-242.properties, gradle-243.properties, gradle-251.properties, gradle.properties
- Update to 2025.1
- Build and verify against 2025.1 on CI
- Update version of the Copilot plugin
=> Build and verify against the final 2025.1 release

appland-navie/package.json, appland-navie/webview.js, appland-navie/yarn.lock, plugin-core/src/main/java/appland/actions/OpenNavieThreadAction.java, plugin-core/src/main/java/appland/rpcService/AppLandJsonRpcService.java, plugin-core/src/main/java/appland/rpcService/DefaultAppLandJsonRpcService.java, plugin-core/src/main/java/appland/rpcService/NavieThreadQueryV1Params.java, plugin-core/src/main/java/appland/rpcService/NavieThreadQueryV1Response.java, plugin-core/src/main/java/appland/webviews/navie/NavieEditor.java, plugin-core/src/main/java/appland/webviews/navie/NavieEditorProvider.java, plugin-core/src/main/resources/META-INF/appmap-core.xml, plugin-core/src/main/resources/messages/appland.properties
This change introduces the ability for users to view and reopen previous Navie chat sessions (threads).
**Key Changes:**
*   **View History Action:** A new action, "AppMap: View Navie History", has been added (accessible via menus/action search).
*   **Thread Selection:** Invoking this action queries the AppMap analysis server (via the JSON-RPC service) for a list of previously saved Navie threads.
*   **UI Popup:** The retrieved threads are presented to the user in a popup list, showing details like the thread title, associated path, and last update time.
*   **Reopen Thread:** Selecting a thread from the list opens the Navie tool window, automatically loading the conversation history for that specific thread.
*   **Backend Communication:** A new JSON-RPC endpoint …
=> feat: Integrate chat history

build.gradle.kts, gradle-241.properties, gradle-242.properties, gradle-243.properties, gradle-251.properties, gradle-252.properties
Unfortunately, we have to use the current snapshot of gradle-intellij-platform-plugin until it has a new stable release. The plugin introduced a breaking change and we have to adapt to fix our build setup.
Also, this PR is adding a workaround for https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1971
It removes the fixed version of the plugin verifier, because the latest available version is now showing the bugs we experienced anymore.
The change to automatically fetch the latest Copilot plugin is unrelated, but helpful.
=> Update Gradle build setup
